### ISSUE TITLE
What is authMode?

### ISSUE THREAD

**Issue by KingRider** [AlexaCRM/php-crm-toolkit#1]
Support CRM Online / On-Promise?

Please me explain

**Comment by wizardist** [comment]
Hi @KingRider!

Yes, indeed, `authMode` designates the type of CRM you're going to connect to. `OnlineFederation` is for CRM Online, and `Federation` is for On-Premises Internet-facing Deployment. Most of settings are documented in [AlexaCRM\CRMToolkit\Settings](https://github.com/AlexaCRM/php-crm-toolkit/blob/master/src/Settings.php).

**Comment by KingRider** [comment]
I see... thanks
