### ISSUE TITLE
Create an email in Dynamics 365 using AlexaCRM php-crm-toolkit

### ISSUE THREAD

**Issue by Matthijs1982** [AlexaCRM/php-crm-toolkit#107]
I'm trying to create an email with php in Dynamics 365 by using the AlexaCRM php-crm toolkit after someone fills in the form on our website. The email also appears in Dynamics, but the from and to fields are empty. The email itself and the subject are stored in Dynamics.

Does anyone had the same problem or does anyone knows what I'm doing wrong?

This is the code I'm using.

```
<?php
require_once '../vendor/autoload.php';

use AlexaCRM\CRMToolkit\Client as OrganizationService;
use AlexaCRM\CRMToolkit\Settings;
use AlexaCRM\CRMToolkit\Client;
use AlexaCRM\CRMToolkit\Entity\MetadataCollection;
use AlexaCRM\CRMToolkit\Entity\EntityReference;

$options = [
    'serverUrl' => 'xxx.dynamics.com',
    'username' => 'xxx@xxx.com',
    'password' => 'xxxxxx',
    'authMode' => 'OnlineFederation',
];

$serviceSettings = new Settings( $options );
$service = new OrganizationService( $serviceSettings );

$email = $service->entity( 'email' );
$email->subject = 'TEST SUBJECT';
$email->description = 'TEST EMAIL';
$email->sender = 'Sender Name';
$email->from = 'test@gmail.com';
$email->to = 'Our Company';
$email->torecipients = 'test@ourcompany.com';
$emailId = $email->create();

?>
```

**Comment by georged** [comment]
Hi @Matthijs1982 

To and from are both of type PartyList, not strings. Check [documentation on email entity](https://docs.microsoft.com/powerapps/developer/common-data-service/reference/entities/email) and accompanying samples. The samples are for SDK or web API but you'll get the idea.

HTH
George

**Comment by Matthijs1982** [comment]
Hi @georged 

I changed my code. But it still doesn't work.

The output shows it correct I think.

I'm sorry for my questions. I'm new to this and this is quite a challenge for me :-(

Code:
```
$email = $service->entity( 'email' );
$email->subject = 'TEST SUBJECT';
$email->description = 'TEST EMAIL';
$email->from = new EntityReference( 'systemuser', ''.$guid.'');
$email->sender = 'CLIENT EMAIL';
$email->to = new EntityReference( 'contact', ''.$guid_stassen.'' );
$email->addressused = 'OUR EMAIL';
$emailId = $email->create();
```

Output from & to:
 [from] => Array
                (
                    [Value] => AlexaCRM\CRMToolkit\Entity\EntityReference Object
                        (
                            [entityLogicalName:protected] => systemuser
                            [entityID:protected] => d82a120e-92e3-ea11-a814-000d3ab8df16
                            [displayName:protected] => 
                            [keyAttributes:protected] => Array
                                (
                                )

                        )

                    [Changed] => 1
                )
[to] => Array
                (
                    [Value] => AlexaCRM\CRMToolkit\Entity\EntityReference Object
                        (
                            [entityLogicalName:protected] => contact
                            [entityID:protected] => ddc0f3b2-b220-ea11-a810-000d3ab5d04f
                            [displayName:protected] => 
                            [keyAttributes:protected] => Array
                                (
                                )

                        )

                    [Changed] => 1
                )

**Comment by georged** [comment]
You're creating EntityReference. From and to fields are PartyList type not EntityReference. As I said, take a look at .NET [samples](https://docs.microsoft.com/en-us/dynamics365/customerengagement/on-premises/developer/sample-work-activity-party-records) in the SDK documentation to get the idea how to build PartyList which is EntityCollection to begin with.

**Comment by Matthijs1982** [comment]
Hi @georged 

Thanks a lot for your help. I tried a lot the couple of days, but it still doesn"t send the email.
The vales of the activityparties are filled in well, but I can't connect the partylists to the to and from fields.

I had a look at the asp samples you referred to and tried the following, but it doesn't work.

Coudl you please help me one more time, as I really don't get it.

```
$toparty = $service->entity("activityparty");
$toparty->partyid = new EntityReference("systemuser", ''.$guid_company.'');
$toparty->addressused = 'ourmail@company.com';

$fromparty = $service->entity("activityparty");
$fromparty->partyid = new EntityReference("systemuser", ''.$guid.'');
$fromparty->addressused = 'customer@domain.com';

$email = $service->entity( 'email' );
$email->subject = 'TEST SUBJECT';
$email->description = 'TEST EMAIL';
$email->to = new EntityCollection($toparty);
$email->from = new EntityCollection($fromparty);
$email->regardingobjectid = new EntityReference("account", ''.$guid.'');
$emailId = $email->create();

```

**Comment by georged** [comment]
Hey @Matthijs1982 

looks like we do have an [issue with activity parties](https://github.com/AlexaCRM/php-crm-toolkit/issues/73), my bad. 

If your Dynamics 365 version supports web api you may want to look at https://github.com/AlexaCRM/dynamics-webapi-toolkit (good idea regardless). Whilst the [issue](https://github.com/AlexaCRM/dynamics-webapi-toolkit/issues/16) does exist and is unresolved at the moment, the issue poster described a workaround.

Cheers
George

**Comment by georged** [comment]
#73

**Comment by Matthijs1982** [comment]
Hi @georged 

Thanks for your help!!
I'll switch to the web api and implement the workaround.

Thanks,
Matthijs
