### ISSUE TITLE
Datetime type field fetch and not coming correct format

### ISSUE THREAD

**Issue by AbhisekBhansali** [AlexaCRM/php-crm-toolkit#109]
Fetch the DOB from contact entity 
        $firstName = $patient->propertyValues['firstname']['Value'];
        $lastName = $patient->propertyValues['lastname']['Value'];
        $dateOfBirth = $patient->propertyValues['birthdate']['Value'];

and set on portal show DOB: -171072000  and the actual date is 7/31/1964

**Comment by georged** [comment]
The value is correct. Datetime values are processes using epoch unix format. You need to convert it before using in UI, see for example https://www.epochconverter.com/programming/php
