### ISSUE TITLE
How to catch if the authentication failed

### ISSUE THREAD

**Issue by dantedantas** [AlexaCRM/php-crm-toolkit#110]
Hello All,

please, could you tell me how could I catch an error at the connection?

![image](https://user-images.githubusercontent.com/10854571/126659551-0c74a13b-14b1-4a69-a6be-238d8626f455.png)

If the user or the password is wrong, I would like to give a friendly information that something went wrong.

Thank you.

Regards,
Dante

**Comment by georged** [comment]
You can issue a small request to validate the connection, e.g. WhoAmI:

```php
try {
   $serviceSettings = new Settings( $options );
   $service = new OrganizationService( $serviceSettings );
   $whoAmIResponse = $service->executeAction( 'WhoAmI' );
}
catch {
}
```
That's what most of the clients that use lazy connections instantiation do, including Microsoft's own.
