### ISSUE TITLE
Get records by date or latest records not all 

### ISSUE THREAD

**Issue by Tameem-Ahmad-com** [AlexaCRM/php-crm-toolkit#111]
Hi i am using you're package in laravel , i need to get  newly created leads  , any solution will be helpful, i am getting all records like contacts or leads but unable to filter because of limited documentation on repo 
 
```
 /**
     * entity set the entity value dynamically
     *
     * @param  mixed $entity
     * @return void
     */
    public function entity($entity)
    {
        $this->entityType = $entity ? $entity : 'lead';
        return $this;
    }

    /**
     * get all entity fields
     *
     * @return void
     */
    public function get()
    {
        $entity = $this->crmClient->retrieveMultipleEntities($this->entityType, $allPages = false, $pagingCookie = null,
        $limitCount = 10, $pageNumber = 1, $simpleMode = false);
        return $entity->Entities??'';
    }
```

**Comment by georged** [comment]
Hi @Tameem-Ahmad-com 

to filter the results you need to use [retrieveMultiple](https://github.com/AlexaCRM/php-crm-toolkit/blob/9bc6569954666e39e95ef79a2e9e0ae5846b9d6f/src/Client.php#L1372) method. First parameter is FetchXml query, you can read more about fetchxml expressions in [Microsoft documenation](https://docs.microsoft.com/powerapps/developer/data-platform/use-fetchxml-construct-query). There are 3rd party tools like [XrmToolBox](https://www.xrmtoolbox.com) that includes [FetchXmlBuilder plugin](https://fetchxmlbuilder.com/) - use these to build and test your expressions.

HTH
