### ISSUE TITLE
Is there any way to fetch opportunities with lineitems 

### ISSUE THREAD

**Issue by Tameem-Ahmad-com** [AlexaCRM/php-crm-toolkit#113]
**i am working on a project where i need to fetch product details with opportunities is this package provide a way to get at least product id or lineitem id with each opportunity.**

**Comment by georged** [comment]
As long as you can retrieve what you need using fetchxml, you can retrieve it with the toolkit. So the answer is yes. First step for you would be to build fetchxml that retrieves the data the you need. We already recommended fetchxml builder previously. Use it.
