### ISSUE TITLE
Uncaught exception 'Exception' with message 'Could not retrieve WSDL

### ISSUE THREAD

**Issue by amanjlucid** [AlexaCRM/php-crm-toolkit#114]
I am using this tool kit for some of my CRM project, I am getting Uncaught exception 'Exception' with message 'Could not retrieve WSDL, Could you please help. Why this message is coming because all my website was working fine till yesterday.

**Comment by arthurbme** [comment]
Using the kit for three years now without issues, but since this morning the same problem (Could not retrieve WDSL ...)

**Comment by AbhisekBhansali** [comment]
D365 CRM Regional Discovery service is deprecated so AlexaCRM/ php-crm-toolkit need to modify the authentication method

**Comment by metadeck** [comment]
We're getting the same issue here for one of our clients sites. Has anyone been able to fix this? Or point us in the direction of whats causing the issue?

**Comment by metadeck** [comment]
This is from a separate repo but its looking like the same issue

https://github.com/AlexaCRM/fetchxml/issues/2

The discovery url ssl certificate looks to be expired.

**Comment by georged** [comment]
We are looking into it. Discovery service is indeed deprecated and should be bypassed.

**Comment by georged** [comment]
Discovery service was removed in 9bc6569, please make sure the package is up to date.
