### ISSUE TITLE
How to create contact with php form on dynamics crm ?

### ISSUE THREAD

**Issue by Mehran16007** [AlexaCRM/php-crm-toolkit#116]
Sorry I'm new to php and dynamics crm how can i use this tool to create contact from a php form on dynamics crm ?

already have php form and with push of submit bottom i want to create contact on dynamics crm.. i use wamp for my php form.

any help is appreciated.

**Comment by Mehran16007** [comment]
this is my php form 


<!DOCTYPE HTML>
<html>

<head>
    <style>
        .error {
            color: #FF0000;
        }
    </style>
</head>

<body>

    <?php
 
require_once 'vendor/autoload.php';

use AlexaCRM\CRMToolkit\Client as OrganizationService;
use AlexaCRM\CRMToolkit\Settings;
use AlexaCRM\CRMToolkit\Entity\EntityReference;

$options = [
    'serverUrl' => '**************************',
    'username' => '**********************',
    'password' => '*****************',
    'authMode' => 'OnlineFederation',
];


$serviceSettings = new Settings( $options );
$service = new OrganizationService( $serviceSettings );

$contact = $service->entity( 'contact' );
$contact->firstname = 'John';
$contact->lastname = 'Doe';
$contact->emailaddress1 = 'john.doe@example.com';
$guid = $contact->create();



    // define variables and set to empty values
    $nameErr = $emailErr = $genderErr = $websiteErr = "";
    $name = $email = $gender = $comment = $website = "";

    if ($_SERVER["REQUEST_METHOD"] == "POST") {
        if (empty($_POST["name"])) {
            $nameErr = "Name is required";
        } else {
            $name = test_input($_POST["name"]);
            // check if name only contains letters and whitespace
            if (!preg_match("/^[a-zA-Z-' ]*$/", $name)) {
                $nameErr = "فقط حروف مجازه";
            }
        }

        if (empty($_POST["email"])) {
            $emailErr = "Email is required";
        } else {
            $email = test_input($_POST["email"]);
            // check if e-mail address is well-formed
            if (!filter_var($email, FILTER_VALIDATE_EMAIL)) {
                $emailErr = "Invalid email format";
            }
        }

        if (empty($_POST["website"])) {
            $website = "";
        } else {
            $website = test_input($_POST["website"]);
            // check if URL address syntax is valid (this regular expression also allows dashes in the URL)
            if (!preg_match("/\b(?:(?:https?|ftp):\/\/|www\.)[-a-z0-9+&@#\/%?=~_|!:,.;]*[-a-z0-9+&@#\/%=~_|]/i", $website)) {
                $websiteErr = "Invalid URL";
            }
        }

        if (empty($_POST["comment"])) {
            $comment = "";
        } else {
            $comment = test_input($_POST["comment"]);
        }

        if (empty($_POST["gender"])) {
            $genderErr = "Gender is required";
        } else {
            $gender = test_input($_POST["gender"]);
        }
    }

    function test_input($data)
    {
        $data = trim($data);
        $data = stripslashes($data);
        $data = htmlspecialchars($data);
        return $data;
    }
    ?>

    <h2>PHP Form Validation Example</h2>
    <p><span class="error">* required field</span></p>
    <form method="post" action="<?php echo htmlspecialchars($_SERVER["PHP_SELF"]); ?>">
        Name: <input type="text" name="name" value="<?php echo $name; ?>">
        <span class="error">* <?php echo $nameErr; ?></span>
        <br><br>
        E-mail: <input type="text" name="email" value="<?php echo $email; ?>">
        <span class="error">* <?php echo $emailErr; ?></span>
        <br><br>
        Website: <input type="text" name="website" value="<?php echo $website; ?>">
        <span class="error"><?php echo $websiteErr; ?></span>
        <br><br>
        Comment: <textarea name="comment" rows="5" cols="40"><?php echo $comment; ?></textarea>
        <br><br>
        Gender:
        <input type="radio" name="gender" <?php if (isset($gender) && $gender == "female") echo "checked"; ?> value="female">Female
        <input type="radio" name="gender" <?php if (isset($gender) && $gender == "male") echo "checked"; ?> value="male">Male
        <input type="radio" name="gender" <?php if (isset($gender) && $gender == "other") echo "checked"; ?> value="other">Other
        <span class="error">* <?php echo $genderErr; ?></span>
        <br><br>
        <input type="submit" name="submit" value="Submit">
    </form>

    <?php
    echo "<h2>Your Input:</h2>";
    echo $name;
    echo "<br>";
    echo $email;
    echo "<br>";
    echo $website;
    echo "<br>";
    echo $comment;
    echo "<br>";
    echo $gender;
    ?>

</body>

</html>

**Comment by Mehran16007** [comment]
![222](https://user-images.githubusercontent.com/95754989/147884335-a82dc151-5c7e-46d4-b835-881be40b34bb.jpg)

how to solve this error?

**Comment by georged** [comment]
@Mehran16007 not sure what the error is as you didn't include it. Are you referring to the unresolved references? Have you run composer as [documented](https://github.com/AlexaCRM/php-crm-toolkit#installation)?

**Comment by Mehran16007** [comment]
> @Mehran16007 not sure what the error is as you didn't include it. Are you referring to the unresolved references? Have you run composer as [documented](https://github.com/AlexaCRM/php-crm-toolkit#installation)?

Thanks for your replay, No i didn't run composer i just copy the toolkit codes into my php form file and i got this error.

**Comment by Mehran16007** [comment]
![wwwwwww](https://user-images.githubusercontent.com/95754989/147910133-568cd26e-1080-4571-97e8-b89f29e4186c.jpg)

**Comment by georged** [comment]
Well, you do need to run composer to bring vendor libraries and references in.

**Comment by Mehran16007** [comment]
> Well, you do need to run composer to bring vendor libraries and references in.

![rrrrrrrr](https://user-images.githubusercontent.com/95754989/147912455-b6034466-2a0b-411b-9379-606855a9e1ee.jpg)



Ok georged, i install composer in my project folder, now i got this error

**Comment by georged** [comment]
Your Dynamics 356 URL is d365.mehran.lab, I assume it's a private Dynamics 365 instance. It must be configured as Internet Facing Deployment instance + it must use https: protocol.

**Comment by Mehran16007** [comment]
> Your Dynamics 356 URL is d365.mehran.lab, I assume it's a private Dynamics 365 instance. It must be configured as Internet Facing Deployment instance + it must use https: protocol.

Ok, So i have to configure IFD internally, am i correct? But i got still same error in my php form code is this normall?

![oooooo](https://user-images.githubusercontent.com/95754989/147913641-673b98ed-b9f2-42ab-9c68-07d8727cbce1.jpg)

**Comment by georged** [comment]
No it's not normal. You have not resolved the references. Have you run composer? Did the vendor folder get created? Does it contain the referenced libraries? This is more or less standard wiring.

**Comment by Mehran16007** [comment]
![1](https://user-images.githubusercontent.com/95754989/147914600-1d21bc80-af7c-4a19-b4b8-d8bf46c205a8.jpg)
![2](https://user-images.githubusercontent.com/95754989/147914608-a9c4f67f-09ca-490a-b2bb-f96992d03181.jpg)
![3](https://user-images.githubusercontent.com/95754989/147914613-b14fa7fa-501e-4e12-b33d-096e324c6a22.jpg)
![4](https://user-images.githubusercontent.com/95754989/147914616-297b9fd1-a108-407d-87a4-99e574dcf95e.jpg)

**Comment by Mehran16007** [comment]
> No it's not normal. You have not resolved the references. Have you run composer? Did the vendor folder get created? Does it contain the referenced libraries? This is more or less standard wiring.

and this is my references, i dont now if it be correct or not 


![Ref](https://user-images.githubusercontent.com/95754989/147914682-31ac59d1-e21b-4566-b698-86c6cab48213.jpg)

**Comment by georged** [comment]
@Mehran16007 you need to run composer. References will not resolve until you do.

`$ composer require alexacrm/php-crm-toolkit:dev-master`

**Comment by Mehran16007** [comment]
> @Mehran16007 you need to run composer. References will not resolve until you do.
> 
> `$ composer require alexacrm/php-crm-toolkit:dev-master`

where should i do that ? i did run this command in cmd with path of my project folder and the command create the vendor folder and composer.json in my project folder but i still get this error, what else shall i do ?


![compose again](https://user-images.githubusercontent.com/95754989/147916636-266ca8e0-12cd-4398-922e-1b4e0666005f.jpg)

**Comment by Mehran16007** [comment]
> @Mehran16007 you need to run composer. References will not resolve until you do.
> 
> `$ composer require alexacrm/php-crm-toolkit:dev-master`

should i change these three path ?  if yes, to where ?


![3path](https://user-images.githubusercontent.com/95754989/147916820-7d14d69b-7a8d-4b07-bf59-e5b0b943c44a.jpg)

**Comment by georged** [comment]
run composer in the same folder as your test php file. that will create **vendor** folder and the references become valid.

**Comment by Mehran16007** [comment]
> run composer in the same folder as your test php file. that will create **vendor** folder and the references become valid.

I already did that George, look at the photos that i sent, here another thing i got this error on my wamp server menu, what is it? how to solve it? is it relate to previous error?

![error](https://user-images.githubusercontent.com/95754989/147918739-52baef76-b3c7-4d5f-ac15-fc03c8c38681.jpg)




when i install composer i chose the wamp php path for the composer, can be for this?

**Comment by Mehran16007** [comment]
May you please remote to my system and see what's going on.

**Comment by Mehran16007** [comment]
> run composer in the same folder as your test php file. that will create **vendor** folder and the references become valid.

I already have **VENDOR** folder in my **test** folder and it has all References

**Comment by georged** [comment]
@Mehran16007 

the issue seems to be your php install/configuration. If you're able to run a simple 'hello, world' php code in the test folder then all references seems to be in place and you should be able to run our sample code as well.

**Comment by Mehran16007** [comment]
> @Mehran16007
> 
> the issue seems to be your php install/configuration. If you're able to run a simple 'hello, world' php code in the test folder then all references seems to be in place and you should be able to run our sample code as well.

There is no problem with running sample hello world or a simple php form in that folder, the problem begin where these two line of code, when i run the program in browser the error is not about that two line error its about the IFD configuration of dynamics crm and the certificate. I'm not php expert may you help me to solve these two line error, maybe with remote to my system as well.

**Comment by georged** [comment]
@Mehran16007 if the errors are about the IFD configuration then it's not a php problem at all. You must have IFD configured and use https otherwise you won't be able to connect to the instance.

**Comment by Mehran16007** [comment]
@georged Where should i put this line **"As a temporary cure, add 'ignoreSslErrors' => true to the Settings."** to not check the certificate ?

**Comment by georged** [comment]
@Mehran16007 this is not the purpose of this flag and it's not going to work. The requirements are clear: the server must be configured for IFD and that includes correct SSL certificate. See [documentation](https://docs.microsoft.com/dynamics365/customerengagement/on-premises/deploy/configure-the-dynamics-365-server-for-ifd)

**Comment by Mehran16007** [comment]
@georged I configure IFD internally but i got this error, i think the error is because of my certificate coz its internal certificate. 

Fatal error: Uncaught Exception: Could not retrieve WSDL at https://mehran.mehran.lab/XRMServices/2011/Organization.svc?wsdl in C:\wamp64\www\test\vendor\alexacrm\php-crm-toolkit\src\Client.php on line 2227

**Comment by Mehran16007** [comment]
@georged  I want to put this flag to not consider the SSL but I don't know where to put this flag ?

**Comment by georged** [comment]
```$options = [
'serverUrl' => '*********',
'username' => '**********************',
'password' => '',
'authMode' => 'OnlineFederation',
ignoreSslErrors => false
];
```
It's not strictly speaking what it's there for but you can try.

**Comment by Mehran16007** [comment]
@georged I test it with value of **True** but got this error.

Fatal error: Uncaught Exception: Invalid SOAP Response: HTTP Response 503 <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN""http://www.w3.org/TR/html4/strict.dtd"> <HTML><HEAD><TITLE>Service Unavailable</TITLE> <META HTTP-EQUIV="Content-Type" Content="text/html; charset=us-ascii"></HEAD> <BODY><h2>Service Unavailable</h2> <hr><p>HTTP Error 503. The service is unavailable.</p> </BODY></HTML> in C:\wamp64\www\test\vendor\alexacrm\php-crm-toolkit\src\Client.php on line 1274

**Comment by georged** [comment]
@Mehran16007 most likely your deployment isn't configured correctly. I'm sorry but this has nothing to do with the toolkit and google is your best friend. For example, this could be one of the reasons : https://support.microsoft.com/topic/http-503-service-unavailable-error-while-accessing-the-microsoft-dynamics-crm-federation-metadata-url-after-configuring-the-claims-based-authentication-6a5dde13-19c3-89d1-f8f5-fe82e0ac7dd7

**Comment by Mehran16007** [comment]
@georged I finally got it working, Thank you for all your replay George, you route me to the correct direction.
