### ISSUE TITLE
Need Query on contact in crm and put condition on create or sending task to crm user

### ISSUE THREAD

**Issue by Mehran16007** [AlexaCRM/php-crm-toolkit#117]
Hi,

when customer fill the form and hit the submit bottom Can I query on telephone1 attribute on contact and if contact exist send task to owner of that record and if contact not exist create the contact in CRM?

Can i do that with calling a custom action in crm? if the answer is yes, how send input parameters and get output parameters?

any help is appreciated.

**Comment by georged** [comment]
@Mehran16007 you can search contact table by using [FetchXml](https://docs.microsoft.com/powerapps/developer/data-platform/use-fetchxml-construct-query) that allows adding conditions on any column including telephone1.  

You can build required FetchXml by using very helpful [FetchXmlBuilder](https://fetchxmlbuilder.com/) and then use [retrieveMultiple method](https://github.com/AlexaCRM/php-crm-toolkit/blob/85572d4670961e4509d39bc9d26a5e9d4e8496e2/src/Client.php#L1497) to retrieve the results.

HTH
