### ISSUE TITLE
Notice: Undefined index: PWD

### ISSUE THREAD

**Issue by mgond** [AlexaCRM/php-crm-toolkit#12]
Whenever I run  my code in cli mode I get the following notice:

`Notice: Undefined index: PWD in ...\vendor\alexacrm\php-crm-toolkit\src\AbstractClient.php on line 101`

This is due to this piece of code from the AbstractClient class

```
$requestDependentData = [
       $_SERVER['PWD'],
];
```

What is expected to be in that variable ?
It seems to work perfectly without any value, wouldn't it be better to check whether or not the variable is defined or not.

Best regards

Mathieu

**Comment by wizardist** [comment]
@mgond removed it completely in 13641fbd78659a13e07190c9725002204ee41e89. Please try again and share your experience.

**Comment by mgond** [comment]
Thanks for the quick answer and fix.
It is working nicely, no more notice.

However, I cannot import your project using composer with version "dev-master" because you added a dependency to psr/log on version "dev-master" which is already require to a stable version in our project. 
Could you change the version of the psr/log requirement or do you really need master version?

Best regards
Mathieu

**Comment by wizardist** [comment]
@mgond yes, we don't need dev-master so bad. I changed it to a straight `*` wildcard.

**Comment by mgond** [comment]
@wizardist thanks, works fine now.
