### ISSUE TITLE
Create new or Update if exists

### ISSUE THREAD

**Issue by mariangrgic** [AlexaCRM/php-crm-toolkit#122]
Hi everyone,

i am buidling script that creates new entities automatically, so i neeed to check if some record already exists bewore creating new one, if it does i need to update existing..
My question is what is proper way to do that?

Should i use fetchXML and retreiveMultiple to perform check before entering new entity record, or there is some other way?

Thanks in advance!

BR

**Comment by georged** [comment]
@mariangrgic client has `upsert` method that does exactly what you described.
