### ISSUE TITLE
Integration broken because disco.crm.dynamics.com is returning 404

### ISSUE THREAD

**Issue by medrawi** [AlexaCRM/php-crm-toolkit#123]
We have an integration with MSD using your repo https://github.com/AlexaCRM/php-crm-toolkit and things used to work just fine

Recently we found that the integration is broken because it is unable to fetch the wsdl info from this URL https://disco.crm.dynamics.com/XRMServices/2011/Discovery.svc?wsdl

By investigating I found that in your repo, at the Settings.php file/class, at the constructor, You have the line below:
$this->discoveryUrl = sprintf( '%s://disco.%[s.dynamics.com/XRMServices/2011/Discovery.svc](http://s.dynamics.com/XRMServices/2011/Discovery.svc)', $serverUrlParts['scheme'], $crmRegionId );

I did a modification to use the account we are connecting to in generating this URL and replace the "disco" pattern by the account's initial pattern, It seems it is returning the wsdl info but the integration is still broken and unable to authenticate.

Could you help me with this?

**Comment by georged** [comment]
@medrawi discovery service has been deprecated by Microsoft long time ago and it's no longer in use (discoveryUrl is built but never used). Please update your code base to make sure you're using the latest version. Also keep in mind that username/password authentication no longer works either, you have to use app id / secret.

**Comment by medrawi** [comment]
@georged Thanks for your response.
This Repo still uses username and password authentication, Any plans to update it to use App ID/Secret?

**Comment by georged** [comment]
@medrawi repo has S2S support, not sure what do you mean. Yes, username support is still there for on-premises solutions but you should be using S2S settings https://github.com/AlexaCRM/php-crm-toolkit/blob/master/src/OnlineS2SSecretAuthenticationSettings.php
