### ISSUE TITLE
Undefined property via __get()

### ISSUE THREAD

**Issue by mapb1990** [AlexaCRM/php-crm-toolkit#15]
I'm getting a next error on run create() method of a custom entity.

>     "Undefined property via __get(): attributes in vendor/alexacrm/php-crm-toolkit/src/Entity.php on line 561"

That error only occours in this entity. in lead or contract works fine.

```
         $paymentEntity = $this->client->entity('custom_payments');
         $paymentEntity->edirect_amount = 1100;
         return $paymentEntity->create();
```

**Comment by wizardist** [comment]
Hi @mapb1990 

Assuming `edirect_amount` is the right name for the field, could you update the library to the latest version and try to reproduce? I cannot locate any statement accessing the Entity attributes on line 561.

**Comment by mapb1990** [comment]
first exception it is in entity construct (vendor/alexacrm/php-crm-toolkit/src/Entity.php:104)

`            foreach ( $this->attributes as $attribute ) {
`

and the second is on call create method (vendor/alexacrm/php-crm-toolkit/src/Entity.php:561)

`            foreach ( $this->attributes as $property => $propertyDetails ) {
`

**Comment by georged** [comment]
@mapb1990 can you make sure you use the latest version because line 561 contains nothing like what you mention. Also, just to make sure we've got the right prefix, can you try something like:

```
$paymentEntity = $this->client->entity('custom_payments');
$paymentEntity->edirect_name = 'Foobar';
return $paymentEntity->create();
```

If that fails, can you upload a screenshot with the list of fields for the `custom_payment` entity (or drop customisation file that includes only that entity)

**Comment by wizardist** [comment]
@mapb1990 could you share your PHP version as well? This looks very odd.
