### ISSUE TITLE
Cannot resolve CRM region: check CRM server url

### ISSUE THREAD

**Issue by ChrisFrench** [AlexaCRM/php-crm-toolkit#16]
I am getting this no matter what I change. Is there something that I might be missing, a tip is coming your way for any help

**Comment by ChrisFrench** [comment]
I was using the auth type.

**Comment by wizardist** [comment]
@ChrisFrench hi, sorry for belated reaction.

What kind of CRM are you trying to use? Is it 365 (online) or On-Premises? Auth type must be `OnlineFederation` for online, and `Federation` for IFD (we support only IFD). Check the examples.

**Comment by ChrisFrench** [comment]
Changing to Federation was the solution thanks!
