### ISSUE TITLE
Cache system | Out-of-the-box testing

### ISSUE THREAD

**Issue by vicentor** [AlexaCRM/php-crm-toolkit#19]
Upon testing the toolkit furthermore, we successfully implemented it using the `README.md` example code.
Aside from the variable `$contactId` that is set at the start yet unused, the rest worked flawlessly.

At the end of the example, there is a snippet about a cache system that we do not understand properly and it generates the following error.
`Fatal error: Class 'Cache' not found in /home/magikweb/public_html/dev/d365/oauth2/index.php on line 41`

![cache-repo](https://cloud.githubusercontent.com/assets/2099885/24216004/0040bfb0-0f11-11e7-83de-b2e3370225c6.png)

Are we missing something? Or that is an example that is not supposed to work unless certain conditions are met?

**Comment by wizardist** [comment]
@vicentor you need to implement the CacheInterface, like make a wrapper around a caching library of your choice. You can just omit caching - NullCache will be used which is a dummy drop-in implementation of CacheInterface which does nothing.

**Comment by vicentor** [comment]
Alright, we will simply comment it for now and see what kind of caching system we can attach to it soon.
Thank you once again, we want to test drive that toolkit and collaborate once we mastered it.
