### ISSUE TITLE
Entity image

### ISSUE THREAD

**Issue by wesiroyife** [AlexaCRM/php-crm-toolkit#2]
Hi!

How can I send image? - "entityimage"
Maybe example?

Thank you!

**Comment by georged** [comment]
When you retrieve entityimage, you get base64 image content. It's up to you how to serve it to the client:

1. You can simply use the image as an embedded content: ```echo "<img src='data:image/png;base64," . $entity->entityimage . "' />"```
2. Save the content into a file or cache and then serve it in a separate request/url.

HTH
