### ISSUE TITLE
Could not retrieve WSDL 

### ISSUE THREAD

**Issue by scf8127** [AlexaCRM/php-crm-toolkit#21]
Our 'authMode  IS 'Federation',

**We got error** 

Internal Server Error

Could not retrieve WSDL at https://org.crmN.dynamics.com/XRMServices/2011/Organization.svc?wsdl

**Comment by wizardist** [comment]
Hi @scf8127 

Well, if you're using Dynamics 365 Online, then your `authMode` is `OnlineFederation`.

**Comment by scf8127** [comment]
HI wizardist,

Thanks for reply.
 i just use first time CRM.

  i use default api key such as

  $contactId = '1d2fc62f-1c56-448b-b546-edfb6d6fec5c';
$options = [
    'serverUrl' => 'https://org.crmN.dynamics.com',
    'username' => 'portal@org.onmicrosoft.com',
    'password' => 'portalPassword',
    'authMode' => 'OnlineFederation',
];

then we got error are below

Internal Server Error

Cannot resolve CRM region: check CRM server ur

Thanks

**Comment by wizardist** [comment]
@scf8127 what does `N` in crmN stand for? What data center are you using?

**Comment by scf8127** [comment]
Thanks for your help.

i Understand Now.
