### ISSUE TITLE
Class Psr\Log\NullLogger not found

### ISSUE THREAD

**Issue by etreml** [AlexaCRM/php-crm-toolkit#22]
Hi team,

first of all applogies because this will be a newbie question.

I've just downloaded your package and entered the configuration values for my on-premise CRM server in the examlple you give in your README.md.

But I receive the error:
Fatal error: Uncaught Error: Class 'Psr\Log\NullLogger' not found in C:\wamp64\www\eww\crm\AlexaCRM\src\Client.php on line 141

I'm not to big with this namespace thing but it seems to me that the Psr\Log\Nullogger class is missing.

What did I do wrong?

Regards,
Edgar

**Comment by wizardist** [comment]
Hi @etreml 

The dependencies of this library are managed by Composer. You should install this lib like this: `composer require alexacrm/php-crm-toolkit`.
