### ISSUE TITLE
Fatal error: Call to a member function critical() on a non-object 

### ISSUE THREAD

**Issue by ekhlascyblance** [AlexaCRM/php-crm-toolkit#23]
Hi 
I have made setup using composer.

I have problem getting contact list.
**Fatal error: Call to a member function critical() on a non-object in** /opt/lampp/htdocs/ekhlas/CRM/vendor/alexacrm/php-crm-toolkit/src/Client.php on line 193

**Comment by wizardist** [comment]
Hi @ekhlascyblance

Please do `composer update` - you're using an outdated edge. This issue should have been fixed earlier.

**Comment by ekhlascyblance** [comment]
ok.
let me try.
then i will tell you.

**Comment by ekhlascyblance** [comment]
Still Same error

**Comment by wizardist** [comment]
@ekhlascyblance please provide the full error message again.

**Comment by ekhlascyblance** [comment]
already provided

**Comment by wizardist** [comment]
@ekhlascyblance please provide the code that you use to employ the library. It would help a lot.

**Comment by ekhlascyblance** [comment]
function __construct( Settings $settings, CacheInterface $cache = null, LoggerInterface $logger = null ) {
        try {
            // Create settings object
            $this->settings = $settings;

            // Inject CacheInterface implementation
            $this->cache = $cache;

            // Inject LoggerInterface implementation
            $this->logger = $logger;

            /* If either mandatory parameter is NULL, throw an Exception */
            if ( !$this->checkConnectionSettings() ) {
                switch ( $this->settings->authMode ) {
                    case "OnlineFederation":
                        throw new BadMethodCallException( get_class( $this ) . ' constructor requires Username and Password' );
                    case "Federation":
                        throw new BadMethodCallException( get_class( $this ) . ' constructor requires the Discovery URI, Username and Password' );
                }
            }
            /* Create authentication class to connect to CRM Online or Internet facing deployment via ADFS */
            switch ( $this->settings->authMode ) {
                case "OnlineFederation":
                    $this->authentication = new OnlineFederation( $this->settings, $this );
                    break;
                case "Federation":
                    $this->settings->loginUrl = $this->getFederationSecurityURI( 'organization' );
                    $this->authentication     = new Federation( $this->settings, $this );
                    break;
            }
            $this->soapActions = new SoapActions( $this );

            if ( !$this->settings->hasOrganizationData() ) {
                $organizationDetails                    = $this->retrieveOrganization( $this->settings->serverUrl );
                $this->settings->organizationId         = $organizationDetails['OrganizationId'];
                $this->settings->organizationName       = $organizationDetails['FriendlyName'];
                $this->settings->organizationUniqueName = $organizationDetails['UniqueName'];
                $this->settings->organizationVersion    = $organizationDetails['OrganizationVersion'];
            }

            /* Initialize the entity metadata instance */
            MetadataCollection::instance( $this );
        } catch ( Exception $e ) {
            $this->logger->critical( 'Caught an exception while initializing PHP CRM Toolkit.', [ 'exception' => $e ] );
            throw $e;
        }
    }
in /src/Client.php

**Comment by ekhlascyblance** [comment]
My Client setting is as below.
http://prntscr.com/frvjyl

**Comment by wizardist** [comment]
This is a listing of Client::__construct(), and I would like to see how you are using the library, e.g. including the autoloader, instantiating the client, making calls, etc.

**Comment by wizardist** [comment]
@ekhlascyblance please change the required version in `composer.json` - replace the `php-crm-toolkit` version with `dev-master` and do `composer update`. You are using an outdated version at the moment.

**Comment by ekhlascyblance** [comment]
you mean Like this

{
    "require": {
        "alexacrm/dev-master": "^1.1"
    }
}

**Comment by wizardist** [comment]
@ekhlascyblance no, please refer to Composer documentation.

Your `composer.json` file would look like:

```
{
    "require": {
        "alexacrm/php-crm-toolkit": "dev-master"
    }
}
```

Then hit the `composer update` command.

**Comment by ekhlascyblance** [comment]
ok .

let me try

**Comment by ekhlascyblance** [comment]
Solved ..
But Got new error now

Class 'Cache' not found 


I use below code  Note :  second Last line

require_once 'vendor/autoload.php';

use AlexaCRM\CRMToolkit\Client as OrganizationService;
use AlexaCRM\CRMToolkit\Settings;

$contactId = '1d2fc62f-1c56-448b-b546-edfb6d6fec5c';
$options = [
    'serverUrl' => 'https://org.crmN.dynamics.com',
    'username' => 'portal@org.onmicrosoft.com',
    'password' => 'portalPassword',
    'authMode' => 'OnlineFederation',
];

$serviceSettings = new Settings( $options );
$service = new OrganizationService( $serviceSettings );

// retrieve a contact and update its fields
$contact = $service->entity( 'contact', $guid );
$contact->firstname = explode( '@', $contact->emailaddress1 )[0];
$contact->update();
printf( 'Info for %s %s updated.', $contact->firstname, $contact->lastname );

// create a new contact
$contact = $service->entity( 'contact' );
$contact->firstname = 'John';
$contact->lastname = 'Doe';
$contact->emailaddress1 = 'john.doe@example.com';
$contactId = $contact->create();

// delete a contact
$contact->delete();

// execute an action
$whoAmIResponse = $service->executeAction( 'WhoAmI' );
echo 'Organization ID: ' . $whoAmIResponse->OrganizationId;

// inject cache repo
// must be instance of AlexaCRM\CRMToolkit\CacheInterface
$cacheRepo = Cache::instance();
$service = new Client( $serviceSettings, $cacheRepo );

**Comment by wizardist** [comment]
@ekhlascyblance yes, about that - just don't provide a `$cacheRepo`. Or you can alternatively implement `CacheInterface` and provide your implementation. This library gives you freedom in this regard.

**Comment by ekhlascyblance** [comment]
can you please give some example of that CacheInterface implementation. 

if i am not wrong it will make response faster.

**Comment by wizardist** [comment]
CacheInterface and StorageInterface are well documented, and the implementation is trivial. I'm afraid I can't provide you a working example at this time. Some examples may be seen here: https://github.com/AlexaCRM/integration-dynamics/blob/master/src/Cache.php

**Comment by ekhlascyblance** [comment]
Ok
Thanks  Bro.
You are really wizard for me
