### ISSUE TITLE
Unable to get entity 'contact' using emailaddress1

### ISSUE THREAD

**Issue by chetan3151** [AlexaCRM/php-crm-toolkit#27]
i am trying to get contact entity using emailaddress1. But this is not able to get contact details using emailaddress1. However GUID works.

contact entity with emailaddress1('firstcontact@hotmail.com') is there.
```
$contactKeyValue = 'firstcontact@hotmail.com';
    if ( filter_var( $contactKeyValue, FILTER_VALIDATE_EMAIL ) ) {
        $isRetrievedByEmail = true;
    }
if ( $isRetrievedByEmail ) {
    $contactKey = new \AlexaCRM\CRMToolkit\KeyAttributes();
    $contactKey->add( 'emailaddress1', $contactKeyValue );
}
$contact = $client->entity( 'contact', $contactKey);
```

Output: Contact not found. Aborting...

**Comment by georged** [comment]
Hi @chetan3151,

do you have `emailaddress1` defined as an alternate key in CRM?

Thanks
George

**Comment by chetan3151** [comment]
I am new to CRM-PHP. Please check this contact response using GUID.

`Retrieving contact information for ID cc870926-8c8c-e711-80c6-000c2983dc59 
AlexaCRM\CRMToolkit\Entity Object
(
    [entityimage:protected] => 
    [localProperties:protected] => Array
        (
        )

    [propertyValues:AlexaCRM\CRMToolkit\Entity:private] => Array
        (
            [preferredcontactmethodcodename] => Array
                (
                    [Value] => Phone
                    [Changed] => 
                )

            [haschildrencodename] => Array
                (
                    [Value] => Default Value
                    [Changed] => 
                )

            [emailaddress2] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [emailaddress1] => Array
                (
                    [Value] => fc@hotmail.com
                    [Changed] => 
                )

            [address3_addresstypecode] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [address1_city] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [address3_line1] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [address1_line1] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [educationcodename] => Array
                (
                    [Value] => Default Value
                    [Changed] => 
                )

            [address1_longitude] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [address2_freighttermscodename] => Array
                (
                    [Value] => Default Value
                    [Changed] => 
                )

            [modifiedon] => Array
                (
                    [Value] => 1503991923
                    [Changed] => 
                )

            [aging90] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [overriddencreatedon] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [yomilastname] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [yomifirstname] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [statuscodename] => Array
                (
                    [Value] => Active
                    [Changed] => 
                )

            [donotpostalmail] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [yomifullname] => Array
                (
                    [Value] => First Contact
                    [Changed] => 
                )

            [createdbyexternalpartyname] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [address1_addresstypecode] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [address3_line2] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [modifiedbyyominame] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [aging30] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [address1_freighttermscode] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [address3_telephone1] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [address3_line3] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [donotsendmm] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [address2_county] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [creditonhold] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [transactioncurrencyidname] => Array
                (
                    [Value] => US Dollar
                    [Changed] => 
                )

            [donotbulkpostalmail] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [aging60_base] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [accountrolecode] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [preferredsystemuseridyominame] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [address1_shippingmethodcode] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [createdby] => Array
                (
                    [Value] => AlexaCRM\CRMToolkit\Entity\EntityReference Object
                        (
                            [entityLogicalName:protected] => systemuser
                            [entityID:protected] => 5aa4e97f-447b-e711-80c1-000c2983dc59
                            [displayName:protected] => Microsoft CRM Admin
                            [keyAttributes:protected] => Array
                                (
                                )

                        )

                    [Changed] => 
                )

            [gendercode] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [address3_utcoffset] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [externaluseridentifier] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [address3_primarycontactname] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [modifiedbyexternalpartyyominame] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [originatingleadid] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [preferredsystemuseridname] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [preferredserviceidname] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [owningbusinessunit] => Array
                (
                    [Value] => AlexaCRM\CRMToolkit\Entity\EntityReference Object
                        (
                            [entityLogicalName:protected] => businessunit
                            [entityID:protected] => 04e45961-7572-e711-80be-000c2983dc59
                            [displayName:protected] => 
                            [keyAttributes:protected] => Array
                                (
                                )

                        )

                    [Changed] => 
                )

            [preferredappointmenttimecode] => Array
                (
                    [Value] => AlexaCRM\CRMToolkit\OptionSetValue Object
                        (
                            [value:protected] => 1
                            [label:protected] => Morning
                        )

                    [Changed] => 
                )

            [preferredappointmentdaycodename] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [address2_stateorprovince] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [participatesinworkflowname] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [accountrolecodename] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [mobilephone] => Array
                (
                    [Value] => 197346468400
                    [Changed] => 
                )

            [parentcustomeridyominame] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [address2_country] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [address2_line2] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [address3_stateorprovince] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [modifiedonbehalfby] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [slaid] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [assistantphone] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [address3_shippingmethodcodename] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [parentcontactid] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [statuscode] => Array
                (
                    [Value] => AlexaCRM\CRMToolkit\OptionSetValue Object
                        (
                            [value:protected] => 1
                            [label:protected] => Active
                        )

                    [Changed] => 
                )

            [onholdtime] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [parentcontactidyominame] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [address3_longitude] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [creditlimit] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [birthdate] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [originatingleadidname] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [address1_utcoffset] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [managerphone] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [employeeid] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [versionnumber] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [donotsendmarketingmaterialname] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [modifiedbyexternalpartyname] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [statecodename] => Array
                (
                    [Value] => Active
                    [Changed] => 
                )

            [address3_upszone] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [customertypecode] => Array
                (
                    [Value] => AlexaCRM\CRMToolkit\OptionSetValue Object
                        (
                            [value:protected] => 1
                            [label:protected] => Default Value
                        )

                    [Changed] => 
                )

            [donotbulkpostalmailname] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [exchangerate] => Array
                (
                    [Value] => 1
                    [Changed] => 
                )

            [address3_composite] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [isprivate] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [telephone3] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [customersizecode] => Array
                (
                    [Value] => AlexaCRM\CRMToolkit\OptionSetValue Object
                        (
                            [value:protected] => 1
                            [label:protected] => Default Value
                        )

                    [Changed] => 
                )

            [preferredcontactmethodcode] => Array
                (
                    [Value] => AlexaCRM\CRMToolkit\OptionSetValue Object
                        (
                            [value:protected] => 3
                            [label:protected] => Phone
                        )

                    [Changed] => 
                )

            [childrensnames] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [address1_addresstypecodename] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [address2_latitude] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [createdon] => Array
                (
                    [Value] => 1503991923
                    [Changed] => 
                )

            [donotbulkemail] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [slaname] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [marketingonlyname] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [donotfax] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [familystatuscodename] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [annualincome_base] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [aging90_base] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [address1_composite] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [firstname] => Array
                (
                    [Value] => First
                    [Changed] => 
                )

            [createdonbehalfby] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [address2_freighttermscode] => Array
                (
                    [Value] => AlexaCRM\CRMToolkit\OptionSetValue Object
                        (
                            [value:protected] => 1
                            [label:protected] => Default Value
                        )

                    [Changed] => 
                )

            [preferredappointmenttimecodename] => Array
                (
                    [Value] => Morning
                    [Changed] => 
                )

            [callback] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [address2_postalcode] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [educationcode] => Array
                (
                    [Value] => AlexaCRM\CRMToolkit\OptionSetValue Object
                        (
                            [value:protected] => 1
                            [label:protected] => Default Value
                        )

                    [Changed] => 
                )

            [lastusedincampaign] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [paymenttermscodename] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [utcconversiontimezonecode] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [processid] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [owneridyominame] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [governmentid] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [isautocreate] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [isbackofficecustomername] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [address2_shippingmethodcodename] => Array
                (
                    [Value] => Default Value
                    [Changed] => 
                )

            [address2_line3] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [description] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [modifiedby] => Array
                (
                    [Value] => AlexaCRM\CRMToolkit\Entity\EntityReference Object
                        (
                            [entityLogicalName:protected] => systemuser
                            [entityID:protected] => 5aa4e97f-447b-e711-80c1-000c2983dc59
                            [displayName:protected] => Microsoft CRM Admin
                            [keyAttributes:protected] => Array
                                (
                                )

                        )

                    [Changed] => 
                )

            [entityimage] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [timezoneruleversionnumber] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [spousesname] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [address1_county] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [createdbyname] => Array
                (
                    [Value] => Microsoft CRM Admin
                    [Changed] => 
                )

            [shippingmethodcodename] => Array
                (
                    [Value] => Default Value
                    [Changed] => 
                )

            [address3_freighttermscode] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [donotemail] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [address3_county] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [address3_freighttermscodename] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [donotphonename] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [pager] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [address2_postofficebox] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [address2_telephone1] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [address2_telephone2] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [address2_telephone3] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [originatingleadidyominame] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [telephone1] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [address1_addressid] => Array
                (
                    [Value] => 30f5df50-c03b-4190-a7ca-8b68d99d3f44
                    [Changed] => 
                )

            [traversedpath] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [customersizecodename] => Array
                (
                    [Value] => Default Value
                    [Changed] => 
                )

            [followemailname] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [entityimage_url] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [annualincome] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [owninguser] => Array
                (
                    [Value] => AlexaCRM\CRMToolkit\Entity\EntityReference Object
                        (
                            [entityLogicalName:protected] => systemuser
                            [entityID:protected] => 5aa4e97f-447b-e711-80c1-000c2983dc59
                            [displayName:protected] => 
                            [keyAttributes:protected] => Array
                                (
                                )

                        )

                    [Changed] => 
                )

            [websiteurl] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [address2_name] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [donotpostalmailname] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [middlename] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [address3_telephone2] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [entityimageid] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [aging60] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [timespentbymeonemailandmeetings] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [parentcustomeridname] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [entityimage_timestamp] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [owneridname] => Array
                (
                    [Value] => Microsoft CRM Admin
                    [Changed] => 
                )

            [creditonholdname] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [address3_shippingmethodcode] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [createdonbehalfbyyominame] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [address2_composite] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [territorycodename] => Array
                (
                    [Value] => Default Value
                    [Changed] => 
                )

            [address1_country] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [customertypecodename] => Array
                (
                    [Value] => Default Value
                    [Changed] => 
                )

            [owningteam] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [address1_stateorprovince] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [address3_addresstypecodename] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [isprivatename] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [paymenttermscode] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [marketingonly] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [modifiedonbehalfbyname] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [preferredequipmentid] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [address1_line3] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [createdbyexternalpartyyominame] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [address1_freighttermscodename] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [slainvokedid] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [mastercontactidname] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [jobtitle] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [nickname] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [transactioncurrencyid] => Array
                (
                    [Value] => AlexaCRM\CRMToolkit\Entity\EntityReference Object
                        (
                            [entityLogicalName:protected] => transactioncurrency
                            [entityID:protected] => c1ba97a5-7672-e711-80be-000c2983dc59
                            [displayName:protected] => US Dollar
                            [keyAttributes:protected] => Array
                                (
                                )

                        )

                    [Changed] => 
                )

            [managername] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [address1_telephone1] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [address1_telephone2] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [address1_telephone3] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [isbackofficecustomer] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [contactid] => Array
                (
                    [Value] => cc870926-8c8c-e711-80c6-000c2983dc59
                    [Changed] => 
                )

            [address2_utcoffset] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [suffix] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [donotemailname] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [slainvokedidname] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [fax] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [masterid] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [mastercontactidyominame] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [assistantname] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [yomimiddlename] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [ownerid] => Array
                (
                    [Value] => AlexaCRM\CRMToolkit\Entity\EntityReference Object
                        (
                            [entityLogicalName:protected] => systemuser
                            [entityID:protected] => 5aa4e97f-447b-e711-80c1-000c2983dc59
                            [displayName:protected] => Microsoft CRM Admin
                            [keyAttributes:protected] => Array
                                (
                                )

                        )

                    [Changed] => 
                )

            [address3_country] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [donotfaxname] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [participatesinworkflow] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [creditlimit_base] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [address2_fax] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [merged] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [owneridtype] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [address2_longitude] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [modifiedbyexternalparty] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [defaultpricelevelid] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [preferredequipmentidname] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [accountid] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [address3_latitude] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [donotphone] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [address1_shippingmethodcodename] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [accountidname] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [address1_primarycontactname] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [statecode] => Array
                (
                    [Value] => AlexaCRM\CRMToolkit\OptionSetValue Object
                        (
                            [value:protected] => 0
                            [label:protected] => Active
                        )

                    [Changed] => 
                )

            [lastonholdtime] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [address1_line2] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [modifiedonbehalfbyyominame] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [company] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [parentcustomerid] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [address2_addresstypecode] => Array
                (
                    [Value] => AlexaCRM\CRMToolkit\OptionSetValue Object
                        (
                            [value:protected] => 1
                            [label:protected] => Default Value
                        )

                    [Changed] => 
                )

            [address2_upszone] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [followemail] => Array
                (
                    [Value] => 1
                    [Changed] => 
                )

            [address3_name] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [address3_fax] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [gendercodename] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [address2_addresstypecodename] => Array
                (
                    [Value] => Default Value
                    [Changed] => 
                )

            [salutation] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [leadsourcecodename] => Array
                (
                    [Value] => Default Value
                    [Changed] => 
                )

            [address1_postalcode] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [createdbyexternalparty] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [stageid] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [address3_telephone3] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [address3_postalcode] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [donotbulkemailname] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [defaultpricelevelidname] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [preferredappointmentdaycode] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [preferredserviceid] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [address2_addressid] => Array
                (
                    [Value] => b2503d83-b6fc-4eca-9201-89377966b738
                    [Changed] => 
                )

            [home2] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [anniversary] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [importsequencenumber] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [address2_city] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [haschildrencode] => Array
                (
                    [Value] => AlexaCRM\CRMToolkit\OptionSetValue Object
                        (
                            [value:protected] => 1
                            [label:protected] => Default Value
                        )

                    [Changed] => 
                )

            [telephone2] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [mergedname] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [subscriptionid] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [familystatuscode] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [department] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [address3_city] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [business2] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [preferredsystemuserid] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [aging30_base] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [address1_name] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [address1_fax] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [address1_latitude] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [address2_shippingmethodcode] => Array
                (
                    [Value] => AlexaCRM\CRMToolkit\OptionSetValue Object
                        (
                            [value:protected] => 1
                            [label:protected] => Default Value
                        )

                    [Changed] => 
                )

            [emailaddress3] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [address3_postofficebox] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [createdonbehalfbyname] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [parentcustomeridtype] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [parentcontactidname] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [modifiedbyname] => Array
                (
                    [Value] => Microsoft CRM Admin
                    [Changed] => 
                )

            [createdbyyominame] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [leadsourcecode] => Array
                (
                    [Value] => AlexaCRM\CRMToolkit\OptionSetValue Object
                        (
                            [value:protected] => 1
                            [label:protected] => Default Value
                        )

                    [Changed] => 
                )

            [address2_line1] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [address1_upszone] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [lastname] => Array
                (
                    [Value] => Contact
                    [Changed] => 
                )

            [accountidyominame] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [shippingmethodcode] => Array
                (
                    [Value] => AlexaCRM\CRMToolkit\OptionSetValue Object
                        (
                            [value:protected] => 1
                            [label:protected] => Default Value
                        )

                    [Changed] => 
                )

            [territorycode] => Array
                (
                    [Value] => AlexaCRM\CRMToolkit\OptionSetValue Object
                        (
                            [value:protected] => 1
                            [label:protected] => Default Value
                        )

                    [Changed] => 
                )

            [ftpsiteurl] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [numberofchildren] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [address1_postofficebox] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [address2_primarycontactname] => Array
                (
                    [Value] => 
                    [Changed] => 
                )

            [fullname] => Array
                (
                    [Value] => First Contact
                    [Changed] => 
                )

            [address3_addressid] => Array
                (
                    [Value] => 2945d26d-ff3f-4cef-bdaf-4095509f3cb8
                    [Changed] => 
                )

        )

    [formattedValues:AlexaCRM\CRMToolkit\Entity:private] => Array
        (
            [customertypecode] => Default Value
            [merged] => No
            [territorycode] => Default Value
            [haschildrencode] => Default Value
            [exchangerate] => 1.0000000000
            [preferredappointmenttimecode] => Morning
            [isbackofficecustomer] => No
            [modifiedon] => 8/29/2017 2:32 PM
            [marketingonly] => No
            [donotphone] => Allow
            [preferredcontactmethodcode] => Phone
            [educationcode] => Default Value
            [customersizecode] => Default Value
            [donotpostalmail] => Allow
            [donotemail] => Allow
            [address2_shippingmethodcode] => Default Value
            [address2_freighttermscode] => Default Value
            [statuscode] => Active
            [createdon] => 8/29/2017 2:32 PM
            [donotsendmm] => Send
            [donotfax] => Allow
            [leadsourcecode] => Default Value
            [creditonhold] => No
            [donotbulkemail] => Allow
            [followemail] => Allow
            [shippingmethodcode] => Default Value
            [donotbulkpostalmail] => No
            [address2_addresstypecode] => Default Value
            [participatesinworkflow] => No
            [statecode] => Active
        )
`

**Comment by georged** [comment]
Hi @chetan3151,

that does not tell us much, unfortunately, just that the contact does 

What I was trying to say is that retrieval by key you're trying to use does not work just for any attribute. It only works for the alternate keys as defined in CRM. To retrieve contact by `emailaddress1` you need to define in CRM an alternate key that includes `emailaddress1`.

Also, you're trying to retrieve contact with email `firstcontact@hotmail.com` whilst the record above has `fc@hotmail.com` as `emailaddress1`.

See https://technet.microsoft.com/en-us/library/dn949335.aspx for more information.

Thanks
George

**Comment by chetan3151** [comment]
Hi @georged ,

Thanks for your quick response. I will read the link given by you and will get back to you soon. 

> Also, you're trying to retrieve contact with email firstcontact@hotmail.com whilst the record above has fc@hotmail.com as emailaddress1.

I just pasted different contact object.

Also I need to find "incident" for specific contact. Can you send me an example how to do this ? How to use EntityReference for such complex queries ?

**Comment by chetan3151** [comment]
Hi @georged ,

I have created emailaddress1 alternate key under keys. Please check the screen here:

![crm alternet key](https://user-images.githubusercontent.com/31477358/29910544-f0fb7836-8e47-11e7-9435-e0bb754629e0.png)

Thanks buddy. This worked for me.
