### ISSUE TITLE
Add/Update values in OptionSet type field like Industry field in Accounts module

### ISSUE THREAD

**Issue by fmahtab** [AlexaCRM/php-crm-toolkit#28]
Hi,

I am trying to add/update the OptionSet value Like 'Industry' in Accounts module but it is not working. Can you please help with the syntax of adding/Updating value of Industry in Accounts module?
Here is my script: 

$serviceSettings = new Settings( $options ); 
$service = new OrganizationService( $serviceSettings );
$account = $service->entity( 'account' );
$account->name = 'ABC Account';
...
...
$account->industrycode= '2';

Thanks!

**Comment by georged** [comment]
Hi @fmahtab 

OptionSet value is an integer, try without quotes: `$account->industrycode= 2;`

HTH

**Comment by fmahtab** [comment]
Thanks @georged, 

I realized we need to typecast the variable to int otherwise a variable with integer value won't work.
$indust = intval($industry);
