### ISSUE TITLE
Undefined Index PWD error

### ISSUE THREAD

**Issue by jkeary** [AlexaCRM/php-crm-toolkit#31]
Hi there.  This library is great.  Thank you for making it, making my life easier for sure.  

I got the following error:

`Undefined index: PWD in /vendor/alexacrm/php-crm-toolkit/src/AbstractClient.php:101
Stack trace:
#0 /vendor/alexacrm/php-crm-toolkit/src/AbstractClient.php(101): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(8, 'Undefined index...', '...', 101, Array)
#1 /vendor/alexacrm/php-crm-toolkit/src/Auth/OnlineFederation.php(211): AlexaCRM\CRMToolkit\AbstractClient::getUuid()
#2 /vendor/alexacrm/php-crm-toolkit/src/Auth/OnlineFederation.php(149): AlexaCRM\CRMToolkit\Auth\OnlineFederation::getLoginXML('https://login.m...', 'crmna:dynamics....', 'username', 'password')
#3 /vendor/alexacrm/php-crm-toolkit/src/Auth/OnlineFederation.php(108): AlexaCRM\CRMToolkit\Auth\OnlineFederation->requestSecurityToken('https://login.m...', 'crmna:dynamics....', 'username', 'password')
#4 /vendor/alexacrm/php-crm-toolkit/src/Client.php(1053): AlexaCRM\CRMToolkit\Auth\OnlineFederation->getDiscoverySecurityToken()
#5 /var/crowdskout/api-worker/vendor/alexacrm/php-crm-toolkit/src/Client.php(1105): AlexaCRM\CRMToolkit\Client->retrieveOrganizations()
#6 /vendor/alexacrm/php-crm-toolkit/src/Client.php(183): AlexaCRM\CRMToolkit\Client->retrieveOrganization('https://...')
#7 /library/Connectors/Connectors/MicrosoftDynamicsConnector.php(74): AlexaCRM\CRMToolkit\Client->__construct(Object(AlexaCRM\CRMToolkit\Settings))`

I printed that `$_SERVER` var out, I don't see the `PWD` var.  It looks to be a bunch of env file variables.  maybe in our particular php Laravel project, our env does not appear to have `PWD` in it.  So, I went ahead and changed the AbstractClient.php file var to a variable we do have in that config, `REQUEST_TIME`, and it now works.  But that may not really be a permanent solution, for everyone.

The other thought I had on this is that when looking into the use of the `$requestDependentData` var, I see that its only really used to create a hash.  For our particular situation we have multiple servers that could be running this code at the same time, and possibly creating the same hash since the `PWD` is the same for both servers.  That is if we had that `PWD` var.

Anyway, just a suggestion, it may be worth changing that one var.  Thanks again!

**Comment by wizardist** [comment]
@jkeary yeah, about that. Could you update your `composer.json` dependency as this:

```
"alexacrm/php-crm-toolkit": "dev-master"
```

You are probably using an old version. We don't use `PWD` any more. In fact, we try to use `random_bytes` and `openssl_random_pseudo_bytes` first, and only then generate GUIDs from garbage we find here and there.

**Comment by jkeary** [comment]
Oh fantastic.  Thanks!
