### ISSUE TITLE
How can I populate values to an optionset field

### ISSUE THREAD

**Issue by fmahtab** [AlexaCRM/php-crm-toolkit#32]
Hi,

I have an optionSet field named 'Category' in Products module and I want to add around 100 values to that optionSet. Is there a way to do that through script?

Thanks!

**Comment by georged** [comment]
@fmahtab 

Using php? Why? What's the scenario? Why wouldn't you use something better? If programming, you can use powershell. Or you can try XrmToolbox to do something like that without coding.

If you insist on php... Well, you'll need to manipulate metadata. It's doable, of course, but personally I wouldn't do it in php.

HTH

**Comment by fmahtab** [comment]
Hi @georged 
Thanks for your help!
I could import the values using import option in MSDynamics but while adding a new product I need to access the value of optionSet for a particular text value. Is it possible to get the value using Alexa Toolkit script?

**Comment by georged** [comment]
@fmahtab 
I don't quite understand. Data import in Dynamics does handle finding optionset by text. In any case, you can use the toolkit to go through metadata and locate optionset value by text.
HTH
