### ISSUE TITLE
Trying to get All Cases for specific contact and all notes for specific case

### ISSUE THREAD

**Issue by cbpatel17** [AlexaCRM/php-crm-toolkit#33]
I have been trying to get all cases for specific contact but i got no success.

Here is my code:

```
$contactKey = new \AlexaCRM\CRMToolkit\KeyAttributes();
$contactKey->add( 'customerid','5e61e646-8c8c-e711-80c6-000c2983dc59' );
$contactKey->add( 'customeridtype',2);

$contact_cases = $client->entity( 'incident', $contactKey);
echo "<pre>";
print_r($contact_cases);exit;
```
Another similar problem when I am trying to get all notes(annotation) for specific case.
Here is my code: 
```
$incidentid= '49243f9c-548e-e711-80c6-000c2983dc59';
$clientOptions  = include( 'config.php' );
$clientSettings = new Settings( $clientOptions );
$client         = new Client( $clientSettings );
$metadata       = MetadataCollection::instance( $client );

    /* $incident = $client->entity( 'incident', $contactKeyvv); */
   $contactKey2 = new \AlexaCRM\CRMToolkit\Entity\EntityReference("incident");
    $contactKey2->__set("ID",$incidentid );

$notes = $client->entity('annotation', $contactKey2);
$isRetrievedByEmail = false;

echo "<pre>";
print_r($notes);
exit;
```
Please help me. I have been trying this for last one month.

**Comment by georged** [comment]
@cbpatel17 

Constructor `Entity($entity, $key)` is designed to support [alternate keys](https://technet.microsoft.com/en-us/library/dn949335.aspx) for entities, it's not designed for retrieval of related records. You need to build fetch xml and use `retrieveMultiple` method to retrieve related records.

HTH
George

**Comment by cbpatel17** [comment]
How do i use that xml fetched into retrieveMultiple method ?

**Comment by georged** [comment]
@cbpatel17 

```
$annotaions = ASDK()->retrieveMultiple( $fetchXML );
foreach ( $annotaions->Entities as $annotation ) {
  echo $annotation->subject;
}
```

**Comment by cbpatel17** [comment]
@georged 

Thanks ... You are just awesome. Thanks thanks thanks..... Problem Solved
