### ISSUE TITLE
error when i connect

### ISSUE THREAD

**Issue by namsir** [AlexaCRM/php-crm-toolkit#35]
Federation and OnlineFederation both gave me same error :( 
serviceSettings = new Settings( $options );
$service = new OrganizationService( $serviceSettings );

Could not find definition of Service <OrganizationService> in provided WSDL

**Comment by georged** [comment]
@namsir 
we need log information to be sure but the behavior indicates that you need to ignore SSL errors. That happens when CA bundle on the hosting server includes invalid certificates (we've seen it on some Azure instances, for example)

HTH
George

**Comment by namsir** [comment]
object(Exception)#7 (7) {
--
  | ["message":protected]=>
  | string(75) "Could not find definition of Service <OrganizationService> in provided WSDL"
  | ["string":"Exception":private]=>
  | string(0) ""
  | ["code":protected]=>
  | int(0)
  | ["file":protected]=>
  | string(71) "C:\xampp\htdocs\dynamics\vendor\alexacrm\php-crm-toolkit\src\Client.php"
  | ["line":protected]=>
  | int(834)
  | ["trace":"Exception":private]=>
  | array(4) {
  | [0]=>
  | array(6) {
  | ["file"]=>
  | string(71) "C:\xampp\htdocs\dynamics\vendor\alexacrm\php-crm-toolkit\src\Client.php"
  | ["line"]=>
  | int(336)
  | ["function"]=>
  | string(18) "findSecurityPolicy"
  | ["class"]=>
  | string(26) "AlexaCRM\CRMToolkit\Client"
  | ["type"]=>
  | string(2) "::"
  | ["args"]=>
  | array(2) {
  | [0]=>
  | object(DOMDocument)#6 (34) {
  | ["doctype"]=>
  | NULL
  | ["implementation"]=>
  | string(22) "(object value omitted)"
  | ["documentElement"]=>
  | NULL
  | ["actualEncoding"]=>
  | NULL
  | ["encoding"]=>
  | NULL
  | ["xmlEncoding"]=>
  | NULL
  | ["standalone"]=>
  | bool(true)
  | ["xmlStandalone"]=>
  | bool(true)
  | ["version"]=>
  | string(3) "1.0"
  | ["xmlVersion"]=>
  | string(3) "1.0"
  | ["strictErrorChecking"]=>
  | bool(true)
  | ["documentURI"]=>
  | NULL
  | ["config"]=>
  | NULL
  | ["formatOutput"]=>
  | bool(false)
  | ["validateOnParse"]=>
  | bool(false)
  | ["resolveExternals"]=>
  | bool(false)
  | ["preserveWhiteSpace"]=>
  | bool(true)
  | ["recover"]=>
  | bool(false)
  | ["substituteEntities"]=>
  | bool(false)
  | ["nodeName"]=>
  | string(9) "#document"
  | ["nodeValue"]=>
  | NULL
  | ["nodeType"]=>
  | int(9)
  | ["parentNode"]=>
  | NULL
  | ["childNodes"]=>
  | string(22) "(object value omitted)"
  | ["firstChild"]=>
  | NULL
  | ["lastChild"]=>
  | NULL
  | ["previousSibling"]=>
  | NULL
  | ["attributes"]=>
  | NULL
  | ["ownerDocument"]=>
  | NULL
  | ["namespaceURI"]=>
  | NULL
  | ["prefix"]=>
  | string(0) ""
  | ["localName"]=>
  | NULL
  | ["baseURI"]=>
  | NULL
  | ["textContent"]=>
  | string(0) ""
  | }
  | [1]=>
  | string(19) "OrganizationService"
  | }
  | }
  | [1]=>
  | array(6) {
  | ["file"]=>
  | string(71) "C:\xampp\htdocs\dynamics\vendor\alexacrm\php-crm-toolkit\src\Client.php"
  | ["line"]=>
  | int(728)
  | ["function"]=>
  | string(36) "getOrganizationAuthenticationAddress"
  | ["class"]=>
  | string(26) "AlexaCRM\CRMToolkit\Client"
  | ["type"]=>
  | string(2) "->"
  | ["args"]=>
  | array(0) {
  | }
  | }
  | [2]=>
  | array(6) {
  | ["file"]=>
  | string(71) "C:\xampp\htdocs\dynamics\vendor\alexacrm\php-crm-toolkit\src\Client.php"
  | ["line"]=>
  | int(176)
  | ["function"]=>
  | string(24) "getFederationSecurityURI"
  | ["class"]=>
  | string(26) "AlexaCRM\CRMToolkit\Client"
  | ["type"]=>
  | string(2) "->"
  | ["args"]=>
  | array(1) {
  | [0]=>
  | string(12) "organization"
  | }
  | }
  | [3]=>
  | array(6) {
  | ["file"]=>
  | string(36) "C:\xampp\htdocs\dynamics\another.php"
  | ["line"]=>
  | int(17)
  | ["function"]=>
  | string(11) "__construct"
  | ["class"]=>
  | string(26) "AlexaCRM\CRMToolkit\Client"
  | ["type"]=>
  | string(2) "->"
  | ["args"]=>
  | array(1) {
  | [0]=>
  | object(AlexaCRM\CRMToolkit\Settings)#4 (25) {
  | ["authMode"]=>
  | string(10) "Federation"
  | ["username"]=>
  | string(43) "synapse@brentwoodindustries.onmicrosoft.com"
  | ["password"]=>
  | string(15) "Syn@PP#2950-CRM"
  | ["serverUrl"]=>
  | string(44) "https://brentwoodindustries.crm.dynamics.com"
  | ["useSsl"]=>
  | bool(true)
  | ["port"]=>
  | string(0) ""
  | ["organizationName"]=>
  | NULL
  | ["organizationId"]=>
  | NULL
  | ["discoveryUrl"]=>
  | string(75) "https://brentwoodindustries.crm.dynamics.com/XRMServices/2011/Discovery.svc"
  | ["organizationUrl"]=>
  | string(78) "https://brentwoodindustries.crm.dynamics.com/XRMServices/2011/Organization.svc"
  | ["organizationDataUrl"]=>
  | string(82) "https://brentwoodindustries.crm.dynamics.com/XRMServices/2011/OrganizationData.svc"
  | ["loginUrl"]=>
  | NULL
  | ["crmRegion"]=>
  | NULL
  | ["organizationUniqueName"]=>
  | NULL
  | ["organizationVersion"]=>
  | NULL
  | ["oauthResource"]=>
  | NULL
  | ["oauthClientId"]=>
  | NULL
  | ["oauthClientSecret"]=>
  | NULL
  | ["oauthGrantType"]=>
  | NULL
  | ["oauthApiVersion"]=>
  | NULL
  | ["oauthAuthorizationEndpoint"]=>
  | NULL
  | ["oauthTokenEndpoint"]=>
  | NULL
  | ["oauthMultiTenant"]=>
  | bool(false)
  | ["ignoreSslErrors"]=>
  | bool(false)
  | ["cache"]=>
  | array(2) {
  | ["server"]=>
  | string(9) "localhost"
  | ["port"]=>
  | int(11211)
  | }
  | }
  | }
  | }
  | }
  | ["previous":"Exception":private]=>
  | NULL
  | }
  | <br />
  | <b>Fatal error</b>:  Uncaught Exception: Could not find definition of Service &lt;OrganizationService&gt; in provided WSDL in C:\xampp\htdocs\dynamics\vendor\alexacrm\php-crm-toolkit\src\Client.php:834
  | Stack trace:
  | #0 C:\xampp\htdocs\dynamics\vendor\alexacrm\php-crm-toolkit\src\Client.php(336): AlexaCRM\CRMToolkit\Client::findSecurityPolicy(Object(DOMDocument), 'OrganizationSer...')
  | #1 C:\xampp\htdocs\dynamics\vendor\alexacrm\php-crm-toolkit\src\Client.php(728): AlexaCRM\CRMToolkit\Client-&gt;getOrganizationAuthenticationAddress()
  | #2 C:\xampp\htdocs\dynamics\vendor\alexacrm\php-crm-toolkit\src\Client.php(176): AlexaCRM\CRMToolkit\Client-&gt;getFederationSecurityURI('organization')
  | #3 C:\xampp\htdocs\dynamics\another.php(17): AlexaCRM\CRMToolkit\Client-&gt;__construct(Object(AlexaCRM\CRMToolkit\Settings))
  | #4 {main}
  | thrown in <b>C:\xampp\htdocs\dynamics\vendor\alexacrm\php-crm-toolkit\src\Client.php</b> on line <b>834</b><br />

**Comment by georged** [comment]
We need log not object dump.
Again, try to set the flag to ignore SSL errors.

**Comment by namsir** [comment]
that worked, thanks :D 

is there a documentation on how to get the json back from this url after i've logged in? I couldn't find it in the examples. Sorry if i'm bugging you because i couldn't find any other sources.

https://brentwoodindustries.crm.dynamics.com/api/data/v8.2/accounts?$filter=bii_activedistributor%20eq%20true&$select=accountid,name,modifiedon,address1_line1,address1_line2,address1_line3,address1_city,address1_postalcode,address1_country,primarycontactid,emailaddress1,telephone1,fax,websiteurl,bii_iddistributor,bii_accuventdist,bii_bulkheaddist,bii_stormtankdist,bii_wheelbarrowdist

**Comment by namsir** [comment]
thanks Georged. I was able to connect to crm and able to fetch xml and get the records i wanted. Awesome, awesome stuff man. You've saved my life :)
