### ISSUE TITLE
Disabling verifyhost is causing a cURL failure

### ISSUE THREAD

**Issue by cburschka-pwc** [AlexaCRM/php-crm-toolkit#36]
We're getting a `cURL Error: Server aborted the SSL handshake` while trying to authenticate (federated IFD). Some investigation tracked it down to the `curl_setopt( $cURLHandle, CURLOPT_SSL_VERIFYHOST, 0 );` line added to `Client::getSoapResponse()` by 4b1f1d89.

Removing this line makes the SSL handshake work correctly.

Is it possible this is a bug in the code? I see that in other places, this option was only set depending on `$this->settings->ignoreSslErrors`, but in this function it is set unconditionally.

**Comment by wizardist** [comment]
Hi @cburschka-pwc 

Are you by any chance running into this problem on OS X?

**Comment by cburschka-pwc** [comment]
Yes, exactly. Is this a quirk in the SSL library then?

**Comment by wizardist** [comment]
@cburschka-pwc refer to the LIMITATIONS section of the curlopt setting page: <https://curl.haxx.se/libcurl/c/CURLOPT_SSL_VERIFYHOST.html>. On DarwinSSL, SNI is disabled if verifyhost is disabled.

On the other hand, not having a conditional clause that checks `ignoreSsl` is a legit error. Would you be so kind to provide a PR that adds a conditional clause on those two statements?

Thanks

**Comment by cburschka-pwc** [comment]
Basically moving these two lines into an if-block, like in the retrieveWsdl() method, I suppose? This certainly fixes the problem we're having. :)
