### ISSUE TITLE
Couldn't authenticate with UserNameWSTrustBinding_IWSTrust13Async in "Federation" mode

### ISSUE THREAD

**Issue by meuhland** [AlexaCRM/php-crm-toolkit#38]
Somehow my on premise setup wouldn't connect with the URI returned by this function in Client.php

``protected function getTrust13UsernameAddress( DOMDocument $authenticationDOM )
 {
        return $this->getTrustAddress( $authenticationDOM, 'UserNameWSTrustBinding_IWSTrust13Async' );
    }
``

But it did start to work when I changed it for "UserNameWSTrustBinding_IWSTrust13Async2" (which uses trust/13/usernamemixed)

**Comment by georged** [comment]
Hi @meuhland 
this does not look like a standard binding. What version of ADFS are you running? 
Cheers
George

**Comment by meuhland** [comment]
ADFS running on Windows 2016 that might be why I was having issues then.

**Comment by georged** [comment]
@meuhland 

interesting... We're focusing our efforts on OAuth in the next release so might have overlooked 2016 server. Can you figure out how to detect and add an `if` around that code? If not, can you send us a copy of the full wsdl so that we could try figuring out how to branch for Windows 2016 server?

Thanks
George

**Comment by georged** [comment]
@meuhland 

Oh, perhaps, we could just try `UserNameWSTrustBinding_IWSTrust13Async2` if `UserNameWSTrustBinding_IWSTrust13Async` returns nothing? Can you validate that and send us a pull request?

**Comment by meuhland** [comment]
Yeah I'll have a look for now I've just patched it locally to make it work... if I remember correctly it did return something just that it was error-ing out.

"An error occured when verifying security for the message" but the moment I switched to Async2 it connected right away.

**Comment by wizardist** [comment]
@meuhland could you give me a list of enabled token endpoints in your AD FS? Endpoints of interest are `username`, `usernamebasictransport` and `usernamemixed`.

**Comment by meuhland** [comment]
@wizardist From where would you get those... I'm drawing a blank.

**Comment by wizardist** [comment]
@meuhland something like this: https://i.stack.imgur.com/VCqP4.png

On a different installation there's a very similar issue, only `UserNameWSTrustBinding_IWSTrust13Async1` is the correct port name. I'd like to confirm.

**Comment by meuhland** [comment]
@wizardist There you go ![image](https://user-images.githubusercontent.com/6123610/39761311-c7d98bd2-52a5-11e8-9bf1-7210879d33e8.png)

**Comment by wizardist** [comment]
@meuhland could you test the latest version against your deployment? Should be fixed.
