### ISSUE TITLE
Set new object property with dynamics 365 using Alexa CRM toolkit

### ISSUE THREAD

**Issue by MssefJian** [AlexaCRM/php-crm-toolkit#40]
I'm using AlexaCRM Toolkit for Dynamics 365, I added a new field for the entity lead with the name new_wordpressid so i can do the mapping with the lead created in wordoress and the lead in dynamics 365 , so when i want to create a new lead using the following code lines 

`$lead= $service->entity('lead');
$lead->firstname = 'john';
$lead->lastname= 'do';
$lead->new_wordpressid = '555';
$lead->create();`

i get the following error : 
 Undefined property via __set() - lead does not support property: new_wordpressid in 
 /var/www/clients/client348/web348/web/wp-content/plugins/dynamics-amcham-crm/dynamics-amcham-crm.php on line 41 in 
/var/www/clients/client348/web348/web/wp-content/plugins/integration-dynamics/vendor/alexacrm/php-crm-toolkit/src/Entity.php on line 261

Adding the new wordpress_id Causes an error. How can i set the wordpress_id Without having Any errors.
 Thank you for your support and interaction

**Comment by georged** [comment]
@MssefJian 

1. have you published customizations since you've added the field?
2. What field type is new_wordpressid?

Thanks
George

**Comment by MssefJian** [comment]
@georged the field type is Text, and yes i publish the customizations

**Comment by MssefJian** [comment]
i really appreciate if someone could help me , i'm stuck with this error since 4 days

**Comment by georged** [comment]
Can you upload a screenshot of the field definition. Form in CRM?

**Comment by MssefJian** [comment]
![amch](https://user-images.githubusercontent.com/18449048/32542240-d39807f2-c469-11e7-84c7-ddfa4fb5cd66.png)

as i said before the field is a custom field

**Comment by wizardist** [comment]
Hi @MssefJian

Could you first update the package to the latest version? Run `composer update alexacrm/php-crm-toolkit` please and try again.

Also, do you employ any caching for `MetadataCollection` by any chance?

**Comment by MssefJian** [comment]
Hi @wizardist 
thank you for your comment , i update the packege and i reconnect to dynamics crm , now it works perfectly
