### ISSUE TITLE
Search Account or Contact by Phone

### ISSUE THREAD

**Issue by jmhabermann** [AlexaCRM/php-crm-toolkit#41]
Hi, 

I'm trying to peform search by Phone, can i do this ?

tks.

**Comment by georged** [comment]
@jmhabermann 

yes, you'd have to use `[fetchxml](https://msdn.microsoft.com/en-us/library/gg328332.aspx)` to find a record by other fields.
Other option is to use [alternate keys](https://technet.microsoft.com/en-us/library/dn949335.aspx) but for the phone number field it's a bit harsh as the alternate key will enforce uniqueness.

Thanks
George

**Comment by jmhabermann** [comment]
ok, thanks, i'll try.
