### ISSUE TITLE
InvalidSecurity Error - retrive

### ISSUE THREAD

**Issue by mtrindade92** [AlexaCRM/php-crm-toolkit#42]
Hi Everyone, 

I get this return from CRM Dynamics:
`<s:envelope xmlns:s="http://www.w3.org/2003/05/soap-envelope" xmlns:a="http://www.w3.org/2005/08/addressing">
   <s:header>
      <a:action s:mustunderstand="1">http://www.w3.org/2005/08/addressing/soap/fault</a:action>
   </s:header>
   <s:body>
      <s:fault>
         <s:code>
            <s:value>s:Sender</s:value>
            <s:subcode>
               <s:value xmlns:a="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd">a:InvalidSecurity</s:value>
            </s:subcode>
         </s:code>
         <s:reason>
            <s:text xml:lang="en-US">An error occurred when verifying security for the message.</s:text>
         </s:reason>
      </s:fault>
   </s:body>
</s:envelope>`

The request sent:
`<?xml version="1.0" encoding="UTF-8"?>
<s:envelope xmlns:s="http://www.w3.org/2003/05/soap-envelope" xmlns:a="http://www.w3.org/2005/08/addressing" xmlns:u="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd">
   <s:header xmlns:default="http://www.w3.org/2001/04/xmlenc#" xmlns:ds="http://www.w3.org/2000/09/xmldsig#" xmlns:o="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd">
      <a:action s:mustunderstand="1">http://schemas.microsoft.com/xrm/2011/Contracts/Discovery/IDiscoveryService/Execute</a:action>
      <sdkclientversion xmlns="http://schemas.microsoft.com/xrm/2011/Contracts">8.1.0.383</sdkclientversion>
      <usertype xmlns="http://schemas.microsoft.com/xrm/2011/Contracts">CrmUser</usertype>
      <a:replyto>
         <a:address>http://www.w3.org/2005/08/addressing/anonymous</a:address>
      </a:replyto>
      <a:messageid>urn:uuid:631344E3-ACD2-6742-4C74-62D5030B026D</a:messageid>
      <a:to s:mustunderstand="1">https://disco.crm2.dynamics.com/XRMServices/2011/Discovery.svc</a:to>
      <o:security s:mustunderstand="1">
         <u:timestamp u:id="_0">
            <u:created>2017-11-09T10:38:31.00Z</u:created>
            <u:expires>2017-11-09T10:43:31.00Z</u:expires>
         </u:timestamp>
         <default:encrypteddata xmlns="http://www.w3.org/2001/04/xmlenc#" id="Assertion0" type="http://www.w3.org/2001/04/xmlenc#Element">
            <default:encryptionmethod algorithm="http://www.w3.org/2001/04/xmlenc#tripledes-cbc">
               <ds:keyinfo>
                  <default:encryptedkey>
                     <default:encryptionmethod algorithm="http://www.w3.org/2001/04/xmlenc#rsa-oaep-mgf1p">
                        <ds:keyinfo id="keyinfo">
                           <o:securitytokenreference xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd">
                              <o:keyidentifier encodingtype="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-soap-message-security-1.0#Base64Binary" valuetype="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-x509-token-profile-1.0#X509SubjectKeyIdentifier"> (hidden)</o:keyidentifier>
                           </o:securitytokenreference>
                        </ds:keyinfo>
                        <default:cipherdata>
                           <default:ciphervalue>(hidden)</default:ciphervalue>
                        </default:cipherdata>
                     </default:encryptionmethod>
                  </default:encryptedkey>
               </ds:keyinfo>
               <default:cipherdata>
                  <default:ciphervalue>(hidden)</default:ciphervalue>
               </default:cipherdata>
            </default:encryptionmethod>
         </default:encrypteddata>
      </o:security>
   </s:header>
   <s:body>
      <execute xmlns="http://schemas.microsoft.com/xrm/2011/Contracts/Discovery" xmlns:i="http://www.w3.org/2001/XMLSchema-instance">
         <request i:type="RetrieveOrganizationsRequest">
            <accesstype>Default</accesstype>
            <release>Current</release>
         </request>
      </execute>
   </s:body>
</s:envelope>`

Can anyone help me?

Thanks a lot!

**Comment by georged** [comment]
@mtrindade92 
check the time on your hosting server. If it's off by more than couple minutes, you will see the error above.
Thanks
George

**Comment by mtrindade92** [comment]
@georged , 

Thanks for your reply.
In our application, PHP is configured the timezone "America/Sao_Paulo" ( -3:00 ).
On CRM Online 2016, is configured the timezone "Brasília" ( -3:00 ).

The problem occurs when AlexaCRM call the follow method: Client::retrieveOrganizations().
Into this method, getSoapResponse method is called too, and the error happens. See below:

`public function retrieveOrganizations() {

		/* Request a Security Token for the Discovery Service */
		$securityToken = $this->authentication->getDiscoverySecurityToken();

		/* Generate a Soap Request for the Retrieve Organization Request method of the Discovery Service */
		$discoverySoapRequest = $this->generateSoapRequest( $this->settings->discoveryUrl, $this->soapActions->getSoapAction( 'discovery', 'Execute' ), $securityToken, SoapRequestsGenerator::generateRetrieveOrganizationRequest() );

               //here the error happen
		$discovery_data = self::getSoapResponse( $this->settings->discoveryUrl, $discoverySoapRequest );`

So, the timezone is the same, what are my alternatives?

Thanks for your help!

**Comment by georged** [comment]
@mtrindade92 

what I meant is that you need to check the **clock** of your hosting server to make sure it's correct. Timezone may be right  but if clock is off by 5 minutes, you'd get the error above.

Thanks
George
