### ISSUE TITLE
Get all contacts

### ISSUE THREAD

**Issue by Silassiai** [AlexaCRM/php-crm-toolkit#43]
How do i get all contacts? And can i filter on lists or something?

**Comment by georged** [comment]
@Silassiai 

you can do that using [fetchxml language](https://msdn.microsoft.com/en-us/library/gg328332.aspx). 

Thanks
George

**Comment by Silassiai** [comment]
uhhhh... ok, and how do i do that and what function do i have to use?

Do i have to add a parameter to this function?

$contacts = $client->retrieveMultipleEntities(
    'contact', $allPages = false, $pagingCookie = null, $limitCount = 10, $pageNumber = 1, $simpleMode = false
);

**Comment by georged** [comment]
@Silassiai 

you can use `retrieveMultipleEntities` which will return all attributes and all records for an entity but this is, generally speaking, not recommended for anything except reference data). 

You need to build your own fetchxml expression and execute it using `retrieveMultiple`.

Thanks
George

**Comment by Silassiai** [comment]
@georged ok thanks!

**Comment by shalemperez** [comment]
> @Silassiai
> 
> you can use `retrieveMultipleEntities` which will return all attributes and all records for an entity but this is, generally speaking, not recommended for anything except reference data).
> 
> You need to build your own fetchxml expression and execute it using `retrieveMultiple`.
> 
> Thanks
> George

There is more documentation for this in the API? i need to use this for a project. Thanks in advance.

**Comment by georged** [comment]
@shalemperez 

if you're using Dynamics 365 Online or Common Data Service, take a look at https://github.com/AlexaCRM/dynamics-webapi-toolkit/. We have a [tutorial for fetchxml](https://github.com/AlexaCRM/dynamics-webapi-toolkit/wiki/Tutorial#fetching-records-via-fetchexpression)

HTH
George
