### ISSUE TITLE
How to query an n:n relationship from Dynamics 365 using Alexa CRM toolkit

### ISSUE THREAD

**Issue by SouhailaHoummadi** [AlexaCRM/php-crm-toolkit#44]
I am developing a wordpress web application and I would like to query a custom many to many relationship from Dynamics 365 using Alexa CRM toolkit.

In fact, I have created a custom Entity called "Working Committees" ( many-to-many relationship with the Entity "Contacts").

I've already created the navigation form displaying contact information and in which I have used these Entities (Screenshot attached).

So, how is It possible to add a new "Working committee" to an existing "Contact" programmatically with PHP ?

Thank you in advance !

![screen_stackoverflow](https://user-images.githubusercontent.com/12673759/33024371-d16b47bc-ce02-11e7-8060-3c9944cc8979.png)

**Comment by georged** [comment]
@SouhailaHoummadi to query N:N relationships, you need to work with [intersect entity](https://msdn.microsoft.com/en-us/library/gg309538.aspx) and build fetchxml returning the data you're after. 

If you're after an example, [this post](https://social.microsoft.com/Forums/en-US/9850d2fa-2044-4a20-b254-f0adccd4c179/fetch-xml-how-to-retrieve-data-with-multiple-linked-entities?forum=crmdevelopment) has a good sample fetchxml that works through N:N relationship.

HTH
George
