### ISSUE TITLE
->update() causing soap error

### ISSUE THREAD

**Issue by syn6UK** [AlexaCRM/php-crm-toolkit#47]
#0 C:\WampDeveloper\Websites\ptl-link.dezrez.com\webroot\vendor\alexacrm\php-crm-toolkit\src\Client.php(2002): AlexaCRM\CRMToolkit\Client-&gt;getSoapResponse('https://testdez...', '&lt;s:Envelope xml...')
#1 C:\WampDeveloper\Websites\ptl-link.dezrez.com\webroot\vendor\alexacrm\php-crm-toolkit\src\Client.php(1726): AlexaCRM\CRMToolkit\Client-&gt;attemptSoapResponse('organization', Object(Closure))
#2 C:\WampDeveloper\Websites\ptl-link.dezrez.com\webroot\vendor\alexacrm\php-crm-toolkit\src\Entity.php(457): AlexaCRM\CRMToolkit\Client-&gt;update(Object(AlexaCRM\CRMToolkit\Entity))

Any Ideas? I've literally followed your guide to the tee. I can read, create and delete just not update.

**Comment by wizardist** [comment]
Hi @syn6UK 

Could you share the code please?

**Comment by syn6UK** [comment]
`$serviceSettings = new Settings( $this->optionstest );
		    $service = new OrganizationService( $serviceSettings );
		    $contactId = '33964A98-7FD6-E711-80DD-005056B21276';
		    $contact = $service->entity( 'contact', $contactId );
		    $contact->firstname = "test";
		    $contact->update();
`

**Comment by wizardist** [comment]
@syn6UK could you also share the text of the exception? You only provided the stack tracke, which doesn't help for now by itself.

**Comment by syn6UK** [comment]
How can I get that? I'm using slim framework.

![image](https://user-images.githubusercontent.com/31861108/34002086-9e28bad4-e0e9-11e7-8834-a5866052317b.png)

**Comment by wizardist** [comment]
@syn6UK please upgrade to the latest version (`@dev-master` in `composer.json` and `composer update`), try again. Then get back with the error message.

**Comment by syn6UK** [comment]
It's still the same error.

![image](https://user-images.githubusercontent.com/31861108/34002879-bae61336-e0eb-11e7-8110-20ff388cf8fc.png)

**Comment by syn6UK** [comment]
{
  "faultcode": "-2147220891",
  "faultstring": "An error occured while processing this request.",
  "faultactor": null,
  "detail": null,
  "faultname": null,
  "headerfault": null
}

Does that mean anything?

**Comment by syn6UK** [comment]
Ok so I've tried doing it from within CRM and I'm getting the same error code with

<OrganizationServiceFault xmlns:i="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://schemas.microsoft.com/xrm/2011/Contracts">
  <ActivityId>4caa3e5d-65bd-4936-838c-9f38dbd56204</ActivityId>
  <ErrorCode>-2147220891</ErrorCode>
  <ErrorDetails xmlns:d2p1="http://schemas.datacontract.org/2004/07/System.Collections.Generic">
    <KeyValuePairOfstringanyType>
      <d2p1:key>OperationStatus</d2p1:key>
      <d2p1:value xmlns:d4p1="http://www.w3.org/2001/XMLSchema" i:type="d4p1:string">0</d2p1:value>
    </KeyValuePairOfstringanyType>
    <KeyValuePairOfstringanyType>
      <d2p1:key>SubErrorCode</d2p1:key>
      <d2p1:value xmlns:d4p1="http://www.w3.org/2001/XMLSchema" i:type="d4p1:string">-2146233088</d2p1:value>
    </KeyValuePairOfstringanyType>
  </ErrorDetails>
  <Message>An error occured while processing this request.</Message>
  <Timestamp>2017-12-14T16:55:53.5268444Z</Timestamp>
  <ExceptionRetriable>false</ExceptionRetriable>
  <ExceptionSource i:nil="true" />
  <InnerFault i:nil="true" />
  <OriginalException i:nil="true" />
  <TraceText>
</TraceText>
</OrganizationServiceFault>

That would tell me its nothing wrong with the kit or anything I've written.

**Comment by georged** [comment]
@syn6UK 

> Ok so I've tried doing it from within CRM and I'm getting the same error code with

I assume you've tried updating the contact using CRM UI. If that's the case then it looks like an unhandled error is thrown by one of the plugins. Not much we can do about it, this is all the information that we get, unfortunately. 

Do you know are there any plugins on the contact entity and what do they do?

Thanks
George

**Comment by syn6UK** [comment]
Sorry for the delay, it was indeed a dodgy plugin on the contact entity causing it. It has been resolved now thanks.
