### ISSUE TITLE
How to Search by fields

### ISSUE THREAD

**Issue by javichuteck** [AlexaCRM/php-crm-toolkit#49]
I need to search on content filtered by a specific field (which is not the ID).

I have tried using "KeyAttributes".
If I use the ID as keyAtribute, I get 1 result.
But if I use another field, it does not bring me results well.

I used the example "cli-contact.php" as a base

```
$ contactKey = new \ AlexaCRM \ CRMToolkit \ KeyAttributes ();
$ contactKey-> add ('emailaddress1', $ contactKeyValue);
```

This is my code:

   ```
$listFilterKey = "listname";
$listFilterValue = "example list 1";

$searchKeyToSearch = new \AlexaCRM\CRMToolkit\KeyAttributes();
$searchKeyToSearch->add( $listFilterKey, $listFilterValue);
    
$resultSearch = $dynamicsClient->entity( 'list', $searchKeyToSearch);
    
if ( !$resultSearch->exists ) {
    echo("List filtered by [".$listFilterKey."] = [".$listFilterValue."] <b>NO RESULTS</b>");
} else {
    echo("RESULTS");
}
```

Thanks!!

**Comment by dantedantas** [comment]
Hi @georged, 

I have the same issue as @javichuteck.
Maybe do you have an example to make it more easy to understand?

In my case I want to search in table "incident".

Thank you in advance.

BR,
Dante

**Comment by dantedantas** [comment]
Hi George.

Thank you very much.
It Works!   :)

Yes, I will start to use the XML ToolBox.

Thanks again.


BR,
Dante


*--*
*Dante Fernandes Dantas*

@: dantedantas@gmail.com
SKYPE: dante.dantas86
AT: +43 0 699 1826 2496

2018-05-14 21:22 GMT+02:00 georged <notifications@github.com>:
