### ISSUE TITLE
' Could not retrieve WSDL' locally

### ISSUE THREAD

**Issue by netdelight** [AlexaCRM/php-crm-toolkit#50]
Hello, I get this error when I test cli-getallcontacts.php locally :
`Fatal error: Uncaught Exception: Could not retrieve WSDL at https://disco.crm4.dynamics.com/XRMServices/2011/Discovery.svc?wsdl in C:\wamp64\www\essenscia\vendor\alexacrm\php-crm-toolkit\src\Client.php on line 1978`
However, the script is working fine when I test it on an online server. Any idea of what's happening ?

**Comment by wizardist** [comment]
Hi @netdelight 

Try adding setting `ignoreSslErrors` to `true` in toolkit settings. I think WAMP CA bundle is broken.

**Comment by netdelight** [comment]
It worked, thanks !

**Comment by katielgc** [comment]
I have the same issue and setting to true didn't sort it! any advice?
