### ISSUE TITLE
Property of the entity cannot be set

### ISSUE THREAD

**Issue by 1pluszone** [AlexaCRM/php-crm-toolkit#55]
Please i am trying to save a new contact into CRM Dynamics 365 but i am getting this error.
I am sure the error is as a result of something that i am not doing right.

![errorcrm](https://user-images.githubusercontent.com/30148973/38087547-6d0ea652-3350-11e8-8566-0215b48997ac.png)

**Comment by wizardist** [comment]
Hi @1pluszone 

`fullname` is a computed read-only field. You must change the concrete fields of the contact, i.e. `firstname` and `lastname`.

**Comment by 1pluszone** [comment]
Thanks @wizardist
Is it possible for me to create my own custom fields?

**Comment by wizardist** [comment]
@1pluszone 

What do you mean? Do you want to customize the entity via PHP code? Or do you want to create/retrieve/update records of entities with custom fields? The latter is available by default, and the former is possible theoretically.

**Comment by 1pluszone** [comment]
My bad @wizardist  
Thanks for the help.
