### ISSUE TITLE
How call crm function

### ISSUE THREAD

**Issue by finellif** [AlexaCRM/php-crm-toolkit#58]
How call a crm function and return RetrieveMultiple.

In an example that someone sent me:

 var fwdFilter = "**pg_DataRVPSet**?$select=pg_DatasRVPId&$filter=pg_ClienteId/Id eq guid'" + accountId + "'";
var oDataEndpointUrl = serverUrl + "/XRMServices/2011/OrganizationData.svc/" + fwdFilter
..
..

How can I use php-crm-toolkit to call "pg_DataRVPSet"

**Comment by georged** [comment]
Hi @finellif 

what you have is Web API sample, current version of our toolkit is SOAP-based. We do have Web API version in the works but it's not available yet.

In the current version of the toolkit you have to use [fetchxml](https://docs.microsoft.com/en-us/dynamics365/customer-engagement/developer/org-service/use-fetchxml-construct-query).

Thanks
George

**Comment by georged** [comment]
Hi @finellif 

I'm not sure what do you mean by "call function". It is possible to use fetchxml to return the same results as the web api call you mentioned. Fetchxml will be something like 

`'<fetch version="1.0" output-format="xml-platform" mapping="logical">
  <entity name="pg_DataRVP" >
    <attribute name="pg_DatasRVPId" />
    <filter>
      <condition attribute="pg_ClienteId" operator="eq" value="' + accountId + '" />
    </filter>
  </entity>
</fetch>'`

Thanks

**Comment by finellif** [comment]
First of all, thank you very much for your time.

How can I use fecthxml with php-crm-toolkit? I do not see anything in the
document

**Comment by georged** [comment]
You just call `retrieveMultiple` method and pass fetchxml to it. Check https://github.com/AlexaCRM/php-crm-toolkit/blob/master/examples/cli-getallcontacts.php sample and replace call `$client->retrieveMultipleEntities("contact",...` with `$client->retrieveMultiple($fetchxml,...`

HTH
George
