### ISSUE TITLE
Adding a contact with attribute...

### ISSUE THREAD

**Issue by ivanraztestki** [AlexaCRM/php-crm-toolkit#59]
Hello.
Your module was very useful and works very well for me, but I have a question about its use.
I want to create contact records and successfully create them with values in their fields (properties). I also want to record attributes for each record.
I did not find in the documentation or in the examples how such attributes can be written to records.
My question is what methods can I use to save attributes?

**Comment by georged** [comment]
@ivanraztestki what do you mean by record attributes? How attributes in your question are different from fields? Can you give me an example?

**Comment by ivanraztestki** [comment]
Hello again. In my admin panel, for example, attributes can be scanned through this subpanel. I want to record such attributes for certain situations.
![23234lk2lkm23](https://user-images.githubusercontent.com/39082916/39866605-fdf5d738-5459-11e8-8326-f6a6345ce917.png)

**Comment by georged** [comment]
@ivanraztestki That does not look like Dynamics 365 Customer Engagement (aka CRM). Please note that's the only system that we support
