### ISSUE TITLE
New Entity

### ISSUE THREAD

**Issue by dantedantas** [AlexaCRM/php-crm-toolkit#60]
Hello everyone. Thank you for this tool. 👍 

Sorry if my question is a little bit basic.
May someone help me to list a new Entity? What should I change?

I am using the example "cli-getallcontacts.php" as the basis to my code.

I changed this line:

`$incidents = $client->retrieveMultipleEntities("incidents", $allPages = false, $pagingCookie = null, $limitCount = 10, $pageNumber = 1, $simpleMode = false);`

But I am geting an error:

> Fatal error: Uncaught AlexaCRM\CRMToolkit\SoapFault: Could not find entity in C:\xampp\htdocs\OC\vendor\alexacrm\php-crm-toolkit\src\Client.php:1164 Stack trace: #0 C:\xampp\htdocs\OC\vendor\alexacrm\php-crm-toolkit\src\Client.php(2007): AlexaCRM\CRMToolkit\Client->getSoapResponse('https://smartst...', '<s:Envelope xml...') #1 C:\xampp\htdocs\OC\vendor\alexacrm\php-crm-toolkit\src\Client.php(794): AlexaCRM\CRMToolkit\Client->attemptSoapResponse('organization', Object(Closure)) #2 C:\xampp\htdocs\OC\vendor\alexacrm\php-crm-toolkit\src\Client.php(770): AlexaCRM\CRMToolkit\Client->retrieveEntityRaw('incidents', NULL, NULL, false) #3 C:\xampp\htdocs\OC\vendor\alexacrm\php-crm-toolkit\src\Entity\MetadataCollection.php(195): AlexaCRM\CRMToolkit\Client->retrieveEntity('incidents') #4 C:\xampp\htdocs\OC\vendor\alexacrm\php-crm-toolkit\src\Entity\MetadataCollection.php(117): AlexaCRM\CRMToolkit\Entity\MetadataCollection->retrieveMetadata('incidents') #5 C:\xampp\htdocs\OC\vendor\alexacrm\php-crm-toolkit\src\Client.php(833): AlexaC in C:\xampp\htdocs\OC\vendor\alexacrm\php-crm-toolkit\src\Client.php on line 1164

Please, may someone help me and shows in what direction should I go?

Thanks to everyone.

BR
Dante

**Comment by georged** [comment]
Hi Dante

Entity name is `incident` (singular), not `incidents`

Thanks 
George

**Comment by dantedantas** [comment]
Hi George. 
Thank you, now it works. 

How may I get the real name of the tables? I am new on Dynamics. I am using this list from the PowerBI App and it shows me the name of the table in the plural as you may see.

![dynamicsincidents](https://user-images.githubusercontent.com/10854571/39986209-4b336628-5761-11e8-91ff-1a2ba88b0440.png)

Now I need to learn how to filter/search an information in a table.

Thank you very much.

BR,
Dante

**Comment by dantedantas** [comment]
Hi George.

Thank you very much!

BR,
Dante

*--*
*Dante Fernandes Dantas*

@: dantedantas@gmail.com
SKYPE: dante.dantas86
AT: +43 0 699 1826 2496

2018-05-14 21:03 GMT+02:00 georged <notifications@github.com>:

**Comment by AnthemPropertiesGroup** [comment]
Hi there,

I tried to use the plugin. I don't see field populate on the form. When I check log files, I see the following error. 

[2020-07-22 16:38:36] crmtoolkit.ERROR: Caught exception while accessing Entity::__get() {"exception":"[object] (AlexaCRM\\CRMToolkit\\SoapFault(code: -2147220969): Could not find entity at /var/www/corp/anthemproperties/web/app/plugins/integration-dynamics/vendor/alexacrm/php-crm-toolkit/src/Client.php:1159)","property":"attributes"} []
[2020-07-22 16:38:36] crmtoolkit.ERROR: Caught exception while creating an Entity object {"exception":"[object] (AlexaCRM\\CRMToolkit\\SoapFault(code: -2147220969): Could not find entity at /var/www/corp/anthemproperties/web/app/plugins/integration-dynamics/vendor/alexacrm/php-crm-toolkit/src/Client.php:1159)"} []

Could you please advice?

Thanks!
PA

**Comment by georged** [comment]
Hi @AnthemPropertiesGroup 

for the plugin-specific issues please use [plugin WordPress forum](https://wordpress.org/support/plugin/integration-dynamics/). When posting there, please provide more information, it looks like a permission error but I may be wrong.

Cheers
George
