### ISSUE TITLE
Authenticating with CRM 2013 on-premises

### ISSUE THREAD

**Issue by jprateragg** [AlexaCRM/php-crm-toolkit#61]
I'm trying out your toolkit with our CRM 2013 on-premises installation. Our CRM installation is only available on network--it's not available when users are out of the building. I'm trying to setup a connection with `authMode => 'Federation'` but it's not working. I keep getting the following error: `Could not find EndorsingSupportingTokens tag in provided security policy XML.` Our installation uses integrated Windows authentication. Is this supported? Thanks!

**Comment by georged** [comment]
Hey @jprateragg

Unfortunately, we don't support AD authentication, we've only implemented and  tested IFD mode. 

We don't get too many requests for AD deployments but another reason for not doing it is that placing your wordpress site, most likely internet facing, on your internal network, is not a very good idea from security point of view.  

Best regards
George
