### ISSUE TITLE
Fatal error:  Allowed memory size

### ISSUE THREAD

**Issue by MssefJian** [AlexaCRM/php-crm-toolkit#62]
Here is the query I'm executing to get all the accounts in Dynamic CRM 365

```
$queryXML = "<fetch mapping='logical' >
	<entity name='account' >
		<all-attributes />
	</entity>
</fetch>";

$accounts = $service->retrieveMultiple($queryXML, false);
```

it gave me this error

Fatal error:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 81666721 bytes) 
in /homepages/30/d577615272/htdocs/wp-content/plugins/integration-dynamics/vendor/alexacrm/php-crm-toolkit/src/Client.php
on line 1143

knowing that I have more than 4000 entries in CRM

**Comment by georged** [comment]
Hi @MssefJian

You’re exhausting the memory. Not sure how we can help. Try pagination and reducing number of columns retrieved.  

Thanks
George

**Comment by MssefJian** [comment]
thank you @georged  for reply

i also try to reducing number of columns by adding this  : 

```
$queryXML = "<fetch mapping='logical' >
                             <entity name='account' >
                                 <attribute name='accountid'/> 
                                 <attribute name='name'/> 
                           </entity>

                      </fetch>";
```

but it shows me the same error

**Comment by georged** [comment]
That’s usual. Try pagination using top attribute  - does that work?

**Comment by MssefJian** [comment]
it doesn't work here is my code

```
$queryXML = "<fetch top='5' >
                    <entity name='account' >
                      <attribute name='name' />
                      <attribute name='emailaddress1' />
                    </entity>
                  </fetch>";
    $accounts = $service->retrieveMultiple($queryXML);
   die(var_dump($accounts));

```
![capture](https://user-images.githubusercontent.com/18449048/40479411-04673e36-5f3b-11e8-9e85-bdbbb6c05e83.PNG)
