### ISSUE TITLE
Call to a member function getElementsByTagName() on null

### ISSUE THREAD

**Issue by euanfergusson** [AlexaCRM/php-crm-toolkit#65]
I am getting the below error in a custom drupal module with relies on alexacrm , it previously worked without issue. 

Having debugged the process a little , it looks like lines on 77/78 arent getting back what would be expected. 

$securityDOM = new \DOMDocument();
$securityDOM->loadXML( $tokenXML );

Call to a member function getElementsByTagName() on null in //vendor/alexacrm/php-crm-toolkit/src/Auth/OnlineFederation.php on line 96

**Comment by wizardist** [comment]
Hi @euanfergusson 

Could you share what you are getting back? What's the response from AAD?

**Comment by euanfergusson** [comment]
never mind, looks like a password issue
