### ISSUE TITLE
Issues with booleans

### ISSUE THREAD

**Issue by andymain** [AlexaCRM/php-crm-toolkit#7]
Similar to the Staus issue the Lable is being pushed up instead of the value, Also 0 is matched as null and not passed. 

Would do a branch and PR but don't have access, could you either allow me to branch/PR or put in the following fix?

Note I'll prob have more going forward.

<img width="850" alt="screen shot 2016-10-27 at 15 07 24" src="https://cloud.githubusercontent.com/assets/1101889/19770426/1a11b6ec-9c57-11e6-84d8-f2470e3f0d8f.png">

**Comment by wizardist** [comment]
@andymain you can fork the repo, create a branch, commit your changes, push them back to your repo and then create a pull request. We'll gladly accept it if everything works fine!

**Comment by andymain** [comment]
#8

**Comment by andymain** [comment]
This issue now appears resolved thanks!
