### ISSUE TITLE
executeAction 'closeIncident' expects Entity not Entity reference and "Incident ID" is missing.

### ISSUE THREAD

**Issue by SlashedAsteroid** [AlexaCRM/php-crm-toolkit#70]
I'm currently having difficulty with the executeAction located in your PHP library.

I am attempting to supply an "IncidentResolution" to a "closeIncident" action, it is reporting it requires the xml type of "Entity" not "EntityReference", however this is not included within the "generateExecuteActionRequest" method located within "SoapRequestsGenerator.php" at line 598.

I was wondering if you could shed some light on the "executeAction" method and what I may be doing wrong as there are no samples for the "executeAction" method.

**Comment by wizardist** [comment]
Hi @SlashedAsteroid 

Unfortunately Entity cannot be serialized at the moment. Would you be willing to provide a pull request?

**Comment by SlashedAsteroid** [comment]
Hi @wizardist,

I ended up getting this working in the end, I've modified SoapRequestsGenerator.php and added the following to the switch statement @ line 629.

` case 'entity':
                        $xmlType = 'Entity';
                        /** @var Entity $entity */
                        $entity      = $xmlValue;
                        $xmlTypeNS   = 'http://schemas.microsoft.com/xrm/2011/Contracts';
                        $entityValue = $executeActionRequestDOM->createElement('c:value');
                        $entityValue->appendChild($executeActionRequestDOM->importNode($entity->getEntityDOM(true )->firstChild, true));
                        $entityValue->appendChild($executeActionRequestDOM->createElement('d:EntityState'))->setAttribute('i:nil', 'true');
                        $entityValue->appendChild($executeActionRequestDOM->createElement('d:FormattedValues'));
                        $entityValue->appendChild($executeActionRequestDOM->createElement('d:Id', $entity->ID));
                        $entityValue->appendChild($executeActionRequestDOM->createElement('d:LogicalName', $entity->LogicalName));
                        $xmlValue = null;
                        break;`

This allowed me the close the case supplying the entity as a scaffold to the request.

**Comment by DrajunoK** [comment]
Hi @SlashedAsteroid 

I'm a bit lost with the executeAction method.
Could you please let me know how did you call the executeAction method to supply an "IncidentResolution" to a "closeIncident" action? (params?)

Thank you.
