### ISSUE TITLE
Unable to create New entry in Appointment Entity of Dynamic CRM 2016

### ISSUE THREAD

**Issue by bhashkar007** [AlexaCRM/php-crm-toolkit#71]
I am trying to create entry in appointment entity but i am getting this error "Argument 1 passed to DOMDocument::importNode() must be an instance of DOMNode, null given" 
this is my code
 $contact = $service->entity( 'appointment' );
and then i have set all necessary argument  then is call this function 
$contactId = $contact->create();
Error arise when i run this function $contact->create(); 
Please suggest me where i am making mistake.

**Comment by georged** [comment]
Hi @bhashkar007 

can you please paste the entire snippet of code you're using to create an appointment? 

Thanks
George

**Comment by bhashkar007** [comment]
@georged 
This is the code which i am using to create appointment entry 

$clientOptions = [
    // Dynamics CRM URL
    'serverUrl' => 'mydynamic.crm.cloudprime.co.uk',
    // System user name
    'username'  => 'username',
    // System user password
    'password'  => 'password',
    // CRM type (OnlineFederation for CRM Online, Federation for IFD)
    'authMode'  => 'Federation',
    'ignoreSslErrors' => true,
];
$clientSettings = new Settings($clientOptions);
$service = new OrganizationService( $clientSettings );
$client = new Client($clientSettings);

$appointment = $service->entity( 'appointment' );

$appointment->actualstart='2019-01-04 8:30';
$appointment->actualend='2019-01-04 9:30';
$appointment->category='Demo';
$appointment->description='Description of meeting goes here.';
$appointment->location='Mumbai India';
$appointment->subject='Subject of meeting goes here';
$appId = $appointment->create();

print_r($appId)

Thanks 
Bhashkar

**Comment by georged** [comment]
@bhashkar007 

you are not setting `scheduledstart` and `scheduledend` which are required for an appointment.

Thanks
George

**Comment by bhashkar007** [comment]
@georged 
I have added this and still i got the same error i am sharing error screenshot with you 
I more thing i am implementing this with Laravel 
This is my code now
 $appointment = $service->entity( 'appointment' );
 $appointment->scheduledstart='2019-01-04 8:30';
 $appointment->scheduledend='2019-01-04 9:30';
 $appointment->actualstart='2019-01-04 8:30';
 $appointment->actualend='2019-01-04 9:30';
 $appointment->category='Demo';
 $appointment->description='Description of meeting goes here.';
 $appointment->location='Mumbai India';
 $appointment->subject='Subject of meeting goes here';
 $appId = $appointment->create();

Here is the screenshot
![error](https://user-images.githubusercontent.com/1473647/50582583-9b47e780-0e89-11e9-8600-a88e6ff032dc.png)

**Comment by wizardist** [comment]
@bhashkar007 please make sure you're running `dev-master` version of the toolkit.

Also, the toolkit expects unixtime integers for DateTime values. Otherwise, your code looks good and is executed correctly.

Regarding null being passed to `generateCreateRequest()`, could you elaborate more on that please? I'm not really sure how that's possible. Do you mean `getEntityDOM()` returns null? That could be a possibility - see the ending of `getEntityDOM()` there might be a suppressed exception - you can either debug manually or pass a logger to the toolkit.

Thanks

**Comment by bhashkar007** [comment]
@wizardist 
In $entity variable there is value but when this function execute it return Null value **$entity->getEntityDOM();** this is the reason i get this error "**Argument 1 passed to DOMDocument::importNode() must be an instance of DOMNode, null given**"
How can i check the issue

**Comment by bhashkar007** [comment]
@georged 
Did you look at this why it is throwing this Error.
I am stuck in this, Please help.
Thanks
Bhashkar

**Comment by georged** [comment]
@bhashkar007 

did you follow the instructions, i.e. 
1. are you running dev-master version of the toolkit.
2. did you supply datetime values as unixtime integers?

Can you paste the updated code that uses unixtime values?

Thanks
George
