### ISSUE TITLE
Uncaught Exception: cURL Error: Operation timed out after 30000 milliseconds

### ISSUE THREAD

**Issue by dantedantas** [AlexaCRM/php-crm-toolkit#72]
Dear Friends,
Maybe my issue is something simple to solve. Or, maybe it is an Apache issue, but, please, could someone help me?

I have a page that load the attachments files from our CRM Incidents.
In some cases, when the Incident has a lot of files, I am getting the error below.

`**Fatal error:** Uncaught Exception: cURL Error: Operation timed out after 30000 milliseconds with 220928942998028288 out of 227045289960144896 bytes received in C:\Tools\xampp\htdocs\incidentreportDEV\vendor\alexacrm\php-crm-toolkit\src\Client.php:1091 Stack trace: #0 C:\Tools\xampp\htdocs\incidentreportDEV\vendor\alexacrm\php-crm-toolkit\src\Client.php(2007): AlexaCRM\CRMToolkit\Client->getSoapResponse('https://smartst...', '<s:Envelope xml...') #1 C:\Tools\xampp\htdocs\incidentreportDEV\vendor\alexacrm\php-crm-toolkit\src\Client.php(1359): AlexaCRM\CRMToolkit\Client->attemptSoapResponse('organization', Object(Closure)) #2 C:\Tools\xampp\htdocs\incidentreportDEV\vendor\alexacrm\php-crm-toolkit\src\Client.php(1271): AlexaCRM\CRMToolkit\Client->retrieveMultipleRaw('<fetch version=...', NULL, NULL, 1) #3 C:\Tools\xampp\htdocs\openjornal\getfiles.php(76): AlexaCRM\CRMToolkit\Client->retrieveMultiple('<fetch version=...', false, NULL, NULL, 1, false) #4 {main} thrown in **C:\Tools\xampp\htdocs\incidentreportDEV\vendor\alexacrm\php-crm-toolkit\src\Client.php on line 1091**`

![image](https://user-images.githubusercontent.com/10854571/51117253-7c444080-180d-11e9-96cc-8df13655f27a.png)

Is possible to increase it? If yes, please, where may I do it?

Thank you in advance.
Best regards,

Dante Dantas

**Comment by georged** [comment]
Hi @dantedantas 

I'd say that looks like timeout due to excessive volume of data. Would be helfpful to see the code you're using on the page but, in general, when dealing with something like that, a crafted [fetchxml using twig](https://docs.alexacrm.com/wpcrm/twig/#fetchxml-queries) usually solves the problem.

Cheers
George

**Comment by dantedantas** [comment]
Hi **@georged**,
thank you for the reply.

Below you may see my code:
![image](https://user-images.githubusercontent.com/10854571/51169129-638a6800-18ab-11e9-9f0c-5509236e93a3.png)

Is a PHP code as you may see. 
![image](https://user-images.githubusercontent.com/10854571/51169483-4ace8200-18ac-11e9-8a70-ecb34ecffed0.png)

May I still use the "TWIG" solution? Please, could you show me how?

Thank you very much.
Best regards,

Dante Dantas

**Comment by wizardist** [comment]
I would suggest just using FetchXML pagination capabilities and download attachments in smaller portions.

https://docs.microsoft.com/en-us/dynamics365/customer-engagement/developer/org-service/page-large-result-sets-with-fetchxml

**Comment by georged** [comment]
In addition to what @wizardist said:

1. You can use twig as documented: https://docs.alexacrm.com/wpcrm/twig/#fetchxml-queries
2. Do not use `<all-attributes>`. I wouldn't try download all attachments at this stage and instead add a link to a page specifically for accessing individual attachments.
