### ISSUE TITLE
How we can create note for a lead with file in attachment using php

### ISSUE THREAD

**Issue by ziyaindia** [AlexaCRM/php-crm-toolkit#75]
Hi Friends,

I am able to create lead successfully.
I want to add note for a lead with some files in attachment.
Please help me to do this.

Thanks in Advance,
Ziya

**Comment by georged** [comment]
1. Create UI to let user upload a file
2. On the server, get uploaded file and create [annotation](https://docs.microsoft.com/en-us/dynamics365/customer-engagement/developer/annotation-note-entity) record linked to the lead

**Comment by ziyaindia** [comment]
Thanks for reply

I am using following UI

URL: https://www.localposh.com/driverSignUp.php


<?php
error_reporting(0);
/**
 * Use init.php if you didn't install the package via Composer
 */
require_once 'vendor/autoload.php';

use AlexaCRM\CRMToolkit\Client as OrganizationService;
use AlexaCRM\CRMToolkit\Settings;
use AlexaCRM\CRMToolkit\Entity\EntityReference;

$options = [
    'serverUrl' => '**********',
    'username' => '*************',
    'password' => '****************',
    'authMode' => 'OnlineFederation',
];

$serviceSettings = new Settings( $options );
$service = new OrganizationService( $serviceSettings );

$firstName = trim($_POST['fDriver']);
$lastName = trim($_POST['lDriver']);
$dob = trim($_POST['dob']);
$mobile = trim($_POST['mobile']);
$emai = trim($_POST['emailDriver']);
$mailing = trim($_POST['mailing']);
$city = trim($_POST['city']);
$state = trim($_POST['state']);
$zip = trim($_POST['zip']);
$ssn = trim($_POST['ssn']);
$license = trim($_POST['license']);
$mode = trim($_POST['modeTransportation']);
$make = trim($_POST['make']);
$model = trim($_POST['model']);
$vehicleRegistration = trim($_POST['vRegister']);
$vin = trim($_POST['vin']);
$color = trim($_POST['color']);
$routing = trim($_POST['routing']);
$account = trim($_POST['account']);
$confirmAccount = trim($_POST['cAccount']);
//$backgroundCheck = trim(($_POST['backgroundCheck']!=='')?$_POST['backgroundCheck']:'');
//$logisticsAgreement = trim(($_POST['logisticsAgreement']!=='')?$_POST['logisticsAgreement']:'');
///$insuranceFile = trim($_FILES['vInsuranceFileUpload']);
//$inspection = trim($_FILES['vInspectionFileUpload']);
//$licenseFile = trim($_FILES['dLicenseFileUpload']);
//$note = trim($_POST['driverNote']);

/*
 * Array
(
    [name] => Ziya Skill.docx
    [type] => application/vnd.openxmlformats-officedocument.wordprocessingml.document
    [tmp_name] => D:\wamp64\tmp\php2D60.tmp
    [error] => 0
    [size] => 15518
)
 */

//echo '<pre>';print_r($_FILES['vInsuranceFileUpload']); echo '</pre>';
$insuranceFile = base64_encode(file_get_contents( $_FILES["vInsuranceFileUpload"]["tmp_name"] ));
$insuranceFileType = $_FILES["vInsuranceFileUpload"]["type"];
$insuranceFileName = $_FILES["vInsuranceFileUpload"]["name"];

$inspection = base64_encode(file_get_contents( $_FILES["vInspectionFileUpload"]["tmp_name"] ));
$licenseFile = base64_encode(file_get_contents( $_FILES["dLicenseFileUpload"]["tmp_name"] ));
// create a new lead

$lead = $service->entity( 'lead' );
$lead->subject='DRIVER SIGN-UP';
$lead->firstname = $firstName;
$lead->lastname = $lastName;
//$lead->fullname = $firstName.' '.$lastName;
$lead->emailaddress1 = $emai;
$lead->mobilephone = $mobile;
$lead->ssc_dob = $dob;									//Personal Info
$lead->emailaddress2 = $mailing;
$lead->address1_city = $city;
$lead->address1_stateorprovince = $state;
$lead->address1_postalcode = $zip;
$lead->new_taxidors = $ssn;					//Personal Info
$lead->new_driverslicense = $license; 			//Personal Info
$lead->ssc_transporttype = $mode;					//Mode of Transportation Field
$lead->new_vehiclemake = $make;									//Mode of Transportation Field
$lead->new_vehiclemodel = $model;								//Mode of Transportation Field - Vehicle Registration/Tag
$lead->new_vinnumber = $vin;									//Mode of Transportation Field - Vin Number
$lead->ssc_color = $color;								//Mode of Transportation Field - color
$lead->new_depositroutingnumber = $routing;							//Bank Deposit Information	- Routing Number				
$lead->new_depositaccountnumber = $account;							//Bank Deposit Information - Account Number
//$lead->confirmAccount = $confirmAccount;				//Bank Deposit Information - Confirm Account Number - Not required for lead creation
//$lead->backgroundCheck = $backgroundCheck;			//AGREE TO BACKGROUND CHECK AUTHORIZATION
//$lead->logisticsAgreement = $logisticsAgreement;		//AGREE TO LOGISTICS SERVICES AGREEMENT
//$lead->insuranceFile = $insuranceFile;				//UPLOAD VEHICLE INSURANCE COVERPAGE
//$lead->inspection = $inspection;						//UPLOAD VEHICLE INSPECTION REPORT
//$lead->licenseFile = $licenseFile;					//UPLOAD DRIVER LICENSE PHOTO
//$lead->note = $note;									//Add a Note

$leadId = $lead->create();


$note = $service->entity('annotation');
//echo '<pre>';print_r($incident);echo '</pre>';
$note->objectid = new EntityReference( 'lead', $leadId );
$note->objecttypecode = 'lead';
$note->subject = 'Note is Created From Lead';
$note->documentbody = $insuranceFile; 
$note->mimetype = "text/plain"; 
$note->notetext = $note;
$note->filename = $insuranceFileName;
//$incident->ID = $guid;//contactid responsiblecontactid primarycontactid
$noteId = $note->create();


echo '<p style="text-align:center; color:green; font-size:12px; font-weight:bold;">Lead created successfully. Lead ID - '.$leadId.'</p>';
?>
<!DOCTYPE html>
<html>

<head>
    <meta charset='utf-8'>
    <meta name='viewport' content='width=device-width initial-scale=1.0'>
    <title>localposh - Driver Signup Success</title>

</head>

<body>
<p style="text-align:center; color:green; font-size:12px; font-weight:bold;"><a href="javascript:void(0);" onclick="history.go(-1);">Back to driver Sign-Up</a></p>
</body>

**Comment by georged** [comment]
You're not base64 encoding file content.

**Comment by ziyaindia** [comment]
I am using 
`$insuranceFile = base64_encode(file_get_contents( $_FILES["vInsuranceFileUpload"]["tmp_name"] ));`

**Comment by georged** [comment]
`$note->objectid = $leadId;`

**Comment by ziyaindia** [comment]
Thanks for your help.......Done by following change
$note->objectid = new EntityReference( 'lead', $leadId );

It's working for single file. I am having multiple files in my request file.

**Comment by georged** [comment]
create multiple annotations

**Comment by ziyaindia** [comment]
Thanks for great help George
