### ISSUE TITLE
Create case or incident for an exiting contact. Can I get CRM contactid by email address using Dynamics CRM Toolkit for PHP?

### ISSUE THREAD

**Issue by ziyaindia** [AlexaCRM/php-crm-toolkit#76]
Hi ALL,
Create case or incident for an exiting contact
I am creating cases for contact by using Dynamics CRM Toolkit for PHP. Can I get CRM contactid by email address? So that i can create case for an exiting contact.

**Comment by georged** [comment]
Yes you can. Depending on your design you'd have to use either [FetchXml](https://docs.microsoft.com/en-us/dynamics365/customer-engagement/developer/org-service/build-queries-fetchxml) or [alternate keys](https://docs.microsoft.com/en-us/dynamics365/customer-engagement/customize/define-alternate-keys-reference-records). The toolkit supports both.

**Comment by ziyaindia** [comment]
Thanks for reply George
How I can write in PHP?

**Comment by georged** [comment]
https://github.com/AlexaCRM/php-crm-toolkit/tree/master/examples

**Comment by georged** [comment]
for fetch:

```
$queryXML = "<fetch>... </fetch>";
$contacts = $service->retrieveMultiple($queryXML, true);
```

**Comment by ziyaindia** [comment]
Thanks George

I got all contacts by following script:

`<?php
require_once 'vendor/autoload.php';

use AlexaCRM\CRMToolkit\Client;
use AlexaCRM\CRMToolkit\Entity\MetadataCollection;
use AlexaCRM\CRMToolkit\Settings;

$isRetrievedByEmail = false;

$clientOptions = include('config.php');
$clientSettings = new Settings($clientOptions);
$client = new Client($clientSettings);
$metadata = MetadataCollection::instance($client);

$contacts = $client->retrieveMultipleEntities("contact", $allPages = false, $pagingCookie = null, $limitCount = 10, $pageNumber = 1, $simpleMode = false);

echo PHP_EOL . '------------------' . PHP_EOL;


foreach ($contacts->Entities as $contact) {

    echo '<pre>';
    print_r($contact);
    echo '</pre>';
    
    echo PHP_EOL . '------------------' . PHP_EOL;
    echo "{$contact->fullname} <{$contact->emailaddress1}>" . PHP_EOL;
    if (!is_null($contact->jobtitle) && !is_null($contact->parentcustomeridname)) {
        echo $contact->jobtitle . ' at ' . $contact->parentcustomeridname . PHP_EOL;
    }
    echo PHP_EOL . $contact->address1_composite . PHP_EOL;
    if (!is_null($contact->telephone1)) {
        echo PHP_EOL . 'Phone: ' . $contact->telephone1 . PHP_EOL;
    }
}`


Getting following error:
"Retrieving contact information for e-mail adam.yaeger6@gmail.com Contact not found. Aborting... "

When I am trying to get a single contact by following script:

`<?php

require_once 'vendor/autoload.php';

use AlexaCRM\CRMToolkit\Client;
use AlexaCRM\CRMToolkit\Entity\MetadataCollection;
use AlexaCRM\CRMToolkit\Settings;

$isRetrievedByEmail = true;
$contactKeyValue = 'adam.yaeger6@gmail.com';

$clientOptions  = include( 'config.php' );
$clientSettings = new Settings( $clientOptions );
$client         = new Client( $clientSettings );
$metadata       = MetadataCollection::instance( $client );

echo 'Retrieving contact information for ' . ( $isRetrievedByEmail ? 'e-mail' : 'ID' ) . ' ' . $contactKeyValue . PHP_EOL;

$contactKey = null;
if ( $isRetrievedByEmail ) {
    $contactKey = new \AlexaCRM\CRMToolkit\KeyAttributes();
    $contactKey->add( 'emailaddress1', $contactKeyValue );
} else {
    $contactKey = $contactKeyValue;
}

$contact = $client->entity( 'contact', $contactKey );
if ( !$contact->exists ) {
    die( 'Contact not found. Aborting...' . PHP_EOL );
}

echo PHP_EOL . '------------------' . PHP_EOL;
echo "{$contact->fullname} <{$contact->emailaddress1}>" . PHP_EOL;
if ( !is_null( $contact->jobtitle ) && !is_null( $contact->parentcustomeridname ) ) {
    echo $contact->jobtitle . ' at ' . $contact->parentcustomeridname . PHP_EOL;
}
echo PHP_EOL . $contact->address1_composite . PHP_EOL;
if ( !is_null( $contact->telephone1 ) ) {
    echo PHP_EOL . 'Phone: ' . $contact->telephone1 . PHP_EOL;
}
`

**Comment by ziyaindia** [comment]
> 
> 
> for fetch:
> 
> ```
> $queryXML = "<fetch>... </fetch>";
> $contacts = $service->retrieveMultiple($queryXML, true);
> ```

Can I get complete guid for fetch XML?

**Comment by ziyaindia** [comment]
Hi George. You are RockStar for this toolkit 👍 

Following script will check a contact for given email address, if contact found it will create a case for existing contact, otherwise create a new contact and then create case. 

`<?php
    /**
     * Use init.php if you didn't install the package via Composer
     */
    require_once 'vendor/autoload.php';

    use AlexaCRM\CRMToolkit\Client as OrganizationService;
    use AlexaCRM\CRMToolkit\Settings;
    use AlexaCRM\CRMToolkit\Client;
    use AlexaCRM\CRMToolkit\Entity\MetadataCollection;
    use AlexaCRM\CRMToolkit\Entity\EntityReference;

    $options  = include( 'config.php' );

    $serviceSettings = new Settings( $options );
    $service = new OrganizationService( $serviceSettings );
    
    
    $clientSettings = new Settings( $options );
    $client         = new Client( $clientSettings );
    $metadata       = MetadataCollection::instance( $client );
    $contactid = '';
    $queryXML = "<fetch version='1.0' output-format='xml-platform' mapping='logical' distinct='false'>
                <entity name='contact'>
                  <attribute name='contactid' />
                  <filter type='and'>
                    <condition attribute='emailaddress1' operator='like' value='%adam.yaeger6@gmail.com%' />
                  </filter>
                </entity>
              </fetch>";


    $contacts = $client->retrieveSingle($queryXML, $allPages = false, $pagingCookie = null, $limitCount = 10, $pageNumber = 1, $simpleMode = false);
    
    if(isset($contacts)) {
        $contactid = $contacts->contactid;
    }
    
    if(trim($contactid) != '') {
        $guid = $contactid;
    } else {
        $contact = $service->entity( 'contact' );
        $contact->firstname = 'John';
        $contact->lastname = 'Doe';
        $contact->emailaddress1 = 'john.doe@example.com';
        $guid = $contact->create();
    }

    $incident = $service->entity('incident');
    //echo '<pre>';print_r($incident);echo '</pre>';
    $incident->title = 'Case Created With Proxy';
    $incident->description = 'This is a test case';
    $incident->customerid = new EntityReference( 'contact', $guid );
    //$incident->ID = $guid;//contactid responsiblecontactid primarycontactid
    $incidentId = $incident->create();
?>`

**Comment by ziyaindia** [comment]
Hi George. You are RockStar for this toolkit :

Following script will check a contact for given email address, if contact found it will create a case for existing contact, otherwise create a new contact and then create case. 

`<?php
    /**
     * Use init.php if you didn't install the package via Composer
     */
    require_once 'vendor/autoload.php';

    use AlexaCRM\CRMToolkit\Client as OrganizationService;
    use AlexaCRM\CRMToolkit\Settings;
    use AlexaCRM\CRMToolkit\Client;
    use AlexaCRM\CRMToolkit\Entity\MetadataCollection;
    use AlexaCRM\CRMToolkit\Entity\EntityReference;

    $options  = include( 'config.php' );

    $serviceSettings = new Settings( $options );
    $service = new OrganizationService( $serviceSettings );
    
    
    $clientSettings = new Settings( $options );
    $client         = new Client( $clientSettings );
    $metadata       = MetadataCollection::instance( $client );
    $contactid = '';
    $queryXML = "<fetch version='1.0' output-format='xml-platform' mapping='logical' distinct='false'>
                <entity name='contact'>
                  <attribute name='contactid' />
                  <filter type='and'>
                    <condition attribute='emailaddress1' operator='like' value='%adam.yaeger6@gmail.com%' />
                  </filter>
                </entity>
              </fetch>";


    $contacts = $client->retrieveSingle($queryXML, $allPages = false, $pagingCookie = null, $limitCount = 10, $pageNumber = 1, $simpleMode = false);
    
    if(isset($contacts)) {
        $contactid = $contacts->contactid;
    }
    
    if(trim($contactid) != '') {
        $guid = $contactid;
    } else {
        $contact = $service->entity( 'contact' );
        $contact->firstname = 'John';
        $contact->lastname = 'Doe';
        $contact->emailaddress1 = 'john.doe@example.com';
        $guid = $contact->create();
    }

    $incident = $service->entity('incident');
    //echo '<pre>';print_r($incident);echo '</pre>';
    $incident->title = 'Case Created With Proxy';
    $incident->description = 'This is a test case';
    $incident->customerid = new EntityReference( 'contact', $guid );
    //$incident->ID = $guid;//contactid responsiblecontactid primarycontactid
    $incidentId = $incident->create();
?>`

**Comment by ziyaindia** [comment]
Hi George. You are RockStar for this toolkit :

Following script will check a contact for given email address, if contact found it will create a case for existing contact, otherwise create a new contact and then create case. 

`<?php
    /**
     * Use init.php if you didn't install the package via Composer
     */
    require_once 'vendor/autoload.php';

    use AlexaCRM\CRMToolkit\Client as OrganizationService;
    use AlexaCRM\CRMToolkit\Settings;
    use AlexaCRM\CRMToolkit\Client;
    use AlexaCRM\CRMToolkit\Entity\MetadataCollection;
    use AlexaCRM\CRMToolkit\Entity\EntityReference;

    $options  = include( 'config.php' );

    $serviceSettings = new Settings( $options );
    $service = new OrganizationService( $serviceSettings );
    
    
    $clientSettings = new Settings( $options );
    $client         = new Client( $clientSettings );
    $metadata       = MetadataCollection::instance( $client );
    $contactid = '';
    $queryXML = "<fetch version='1.0' output-format='xml-platform' mapping='logical' distinct='false'>
                <entity name='contact'>
                  <attribute name='contactid' />
                  <filter type='and'>
                    <condition attribute='emailaddress1' operator='like' value='%adam.yaeger6@gmail.com%' />
                  </filter>
                </entity>
              </fetch>";


    $contacts = $client->retrieveSingle($queryXML, $allPages = false, $pagingCookie = null, $limitCount = 10, $pageNumber = 1, $simpleMode = false);
    
    if(isset($contacts)) {
        $contactid = $contacts->contactid;
    }
    
    if(trim($contactid) != '') {
        $guid = $contactid;
    } else {
        $contact = $service->entity( 'contact' );
        $contact->firstname = 'John';
        $contact->lastname = 'Doe';
        $contact->emailaddress1 = 'john.doe@example.com';
        $guid = $contact->create();
    }

    $incident = $service->entity('incident');
    //echo '<pre>';print_r($incident);echo '</pre>';
    $incident->title = 'Case Created With Proxy';
    $incident->description = 'This is a test case';
    $incident->customerid = new EntityReference( 'contact', $guid );
    //$incident->ID = $guid;//contactid responsiblecontactid primarycontactid
    $incidentId = $incident->create();
?>`
