### ISSUE TITLE
get all updated rows with retrieveMultiple

### ISSUE THREAD

**Issue by babininja** [AlexaCRM/php-crm-toolkit#77]
Hi there. i want to get all contacts that their updated at is today. how do i do that?

**Comment by georged** [comment]
Hi @babininja 

you needto use fetchxml. Once you build your fetchxml then

```
$queryXML = "<fetch>... </fetch>";
$contacts = $service->retrieveMultiple($queryXML, true);
```

Thanks

**Comment by babininja** [comment]
what would i put inside fetch tag?

**Comment by georged** [comment]
Hi @babininja 

you'll find more information about fetchxml in [Build queries with FetchXML](https://docs.microsoft.com/en-us/dynamics365/customer-engagement/developer/org-service/build-queries-fetchxml).

Thanks
George
