### ISSUE TITLE
When I am creating lead using toolkit, lead DOB field is not inserting correctly

### ISSUE THREAD

**Issue by ziyaindia** [AlexaCRM/php-crm-toolkit#78]
When I am creating lead using toolkit, lead DOB field is not inserting correctly

**Comment by georged** [comment]
The toolkit expects unixtime integers for DateTime values. Make sure you convert before inserting.

**Comment by ziyaindia** [comment]
Great Thanks Georged 👍

**Comment by ziyaindia** [comment]
Closed 🥇
