### ISSUE TITLE
Advanced Usage Examples?

### ISSUE THREAD

**Issue by Artemy-Matvienko** [AlexaCRM/php-crm-toolkit#80]
I'm trying to populate a lookup field, for example, which isn't covered in the usage examples:
```
$contact = $service->entity( 'contact' );
$contact->firstname = 'Test';
$contact->lastname = 'TEST';
$contact->emailaddress1 = 'test.test@example.com';
//--- link to account ---
// <insert code here>
//------------------------
$contactId = $contact->create();
```
Option 1 works, although relatively slowly:
```
$account = $service->entity( 'account', 'd9f61377-c1de-e411-80f3-005056a76201' );
$contact->parentcustomerid = $account;
```
Option 2 doesn't:
```
$contact->parentcustomerid = 'd9f61377-c1de-e411-80f3-005056a76201';
```
Is there a better and faster way to do this link?
Also, is there general documentation that was used in the creation of this library that all libraries tend to use and, therefore, don't need to explicitly cover edge use cases for in their docs?

**Comment by georged** [comment]
```
$incident->customerid = new EntityReference( 'account', 'd9f61377-c1de-e411-80f3-005056a76201' );
```

**Comment by Artemy-Matvienko** [comment]
Is there general documentation that was used in the creation of this library that all CRM libraries tend to use and, therefore, don't need to explicitly cover edge use cases for in their docs?

**Comment by georged** [comment]
@Artemy-Matvienko this library is built on top of SOAP API for Dynamics 365, and models [IOrganizationService](https://docs.microsoft.com/en-us/dotnet/api/microsoft.xrm.sdk.iorganizationservice?view=dynamics-general-ce-9) functionality. [This](https://docs.microsoft.com/en-us/dynamics365/customer-engagement/developer/use-microsoft-dynamics-365-organization-service) is a good entry point to explore the documentation.
