### ISSUE TITLE
unable to send date field to dynamics 365 

### ISSUE THREAD

**Issue by wendyrepez** [AlexaCRM/php-crm-toolkit#81]
Hi,

I'm trying to send date fields to CRM in diferent ways and none of them had worked so far.
Any time I check on dynamic 365 I'm seeing this default value "31/12/1969".

I have  tried setting the timezone and  changing date format multiple times without luck. 
Can you please give me an example which works?

I'll appreciated it.

**Comment by georged** [comment]
Hi @wendyrepez 

the datetime is expected in *nix format so the following should work

```
$datetime = new DateTime();
$contact->birthdate = $datetime->getTimestamp();
```

Thanks
George

**Comment by wendyrepez** [comment]
Thanks @georged, it worked! <3!!
