### ISSUE TITLE
Uncaught Exception: Could not find EndorsingSupportingTokens tag in provided security policy XML

### ISSUE THREAD

**Issue by Rgodinho22** [AlexaCRM/php-crm-toolkit#82]
Im having this error message with this log

Fatal error: Uncaught Exception: Could not find EndorsingSupportingTokens tag in provided security policy XML in alexacrm\php-crm-toolkit\src\Client.php:340 Stack trace: #0 alexacrm\php-crm-toolkit\src\Client.php(308): AlexaCRM\CRMToolkit\Client->getSecurityAddress(Object(DOMElement), 'Federation') #1 alexacrm\php-crm-toolkit\src\Client.php(624): AlexaCRM\CRMToolkit\Client->getOrganizationAuthenticationAddress() #2 alexacrm\php-crm-toolkit\src\Client.php(160): AlexaCRM\CRMToolkit\Client->getFederationSecurityURI('organization') #3 alexacrm\php-crm-toolkit\examples\teste.php(19): AlexaCRM\CRMToolkit\Client->__construct(Object(AlexaCRM\CRMToolkit\Settings)) #4 {main} thrown in alexacrm\php-crm-toolkit\src\Client.php on line 340

my code

`<?php 

require_once '../../../autoload.php';

use AlexaCRM\CRMToolkit\Client as OrganizationService;
use AlexaCRM\CRMToolkit\Settings;

$options = [
    'serverUrl' => 'https://xxxx.company.com/XRMServices/2011/Organization.svc',
    'username' => 'user',
    'password' => '****',
    'authMode' => 'Federation',
    
];

$serviceSettings = new Settings( $options );
$service = new OrganizationService( $serviceSettings );
/*
$contact = $service->entity( 'contact', $contactid );
echo "{$contact->fullname}" . PHP_EOL;*/
?>`

**Comment by georged** [comment]
Hi @Rgodinho22 

`serverUrl` is literally server url not service endpoint. Try this:

```
$options = [
'serverUrl' => 'https://xxxx.company.com/',
'username' => 'user',
'password' => '****',
'authMode' => 'Federation',
];
```

Thanks

**Comment by Rgodinho22** [comment]
i had the same error

**Comment by georged** [comment]
do you have your organization configured for IFD? If yes, could you email your org url to support@alexacrm.com?

**Comment by Rgodinho22** [comment]
the configuration is CRM On-premise

**Comment by georged** [comment]
Let me repeat the question: have you configured IFD?
See [docs](https://docs.microsoft.com/en-us/dynamics365/customer-engagement/on-premises/configure-an-internet-facing-deployment)

If not then note that IFD is required. 
If yes, email your organization url to support@alexacrm.com

**Comment by Rgodinho22** [comment]
How i know IFD is configured?

**Comment by georged** [comment]
If IFD is configured, the prompt to login is a form
If IFD is not configured then the prompt is basic prompt (dialog) by the browser
Read the [docs](https://docs.microsoft.com/en-us/dynamics365/customer-engagement/on-premises/configure-an-internet-facing-deployment)

**Comment by Rgodinho22** [comment]
its the second option, it prompt a basic dialog to login on browser.
