### ISSUE TITLE
add contact with product

### ISSUE THREAD

**Issue by Tidada** [AlexaCRM/php-crm-toolkit#87]
Hello, first thank you for that perfect plugin it helps alot,
So, i want to add Contact (entity contact) and this one contain a field called(new_produit_demande) and it's assigned to another entity(new_produituic)

How can i create a contact with that contraint

this is the code that i m trying to use for this case:
<?php 
 require 'autoload.php' ;
 use AlexaCRM\CRMToolkit\Client as OrganizationService;
 use AlexaCRM\CRMToolkit\Settings;
 $options = [
 'serverUrl' => 'https://xxxxx',
              'username' => 'xxxx',
              'password' => 'xxxx',
              'authMode' => 'xxx',

];
$serviceSettings = new Settings( $options );
$service = new OrganizationService( $serviceSettings );
$guid = 'd5bac140-b68b-e911-80cc-005056aa3849';
  $contact = $service->entity('contact');
$contact->firstname='product1';
$contact->new_produit_demande = new EntityReference('new_produituic',$guid);
$contactId = $contact->create();

Cheers

**Comment by georged** [comment]
Code looks fine, as long as the lookup guid is correct. Are you getting any error? What is it?

**Comment by Tidada** [comment]
Fatal error: Uncaught exception 'AlexaCRM\CRMToolkit\SoapFault' with message 'Principal user (Id=0fdb9f17-4c5c-e911-80c1-005056aa3849, type=8) is missing prvAppendTonew_produituic privilege (Id=9f11bbd6-dcab-4764-9dbc-86fa5657f02a)' in C:\xampp\htdocs\uic\alexacrm\php-crm-toolkit\src\Client.php:1159 Stack trace: #0 C:\xampp\htdocs\uic\alexacrm\php-crm-toolkit\src\Client.php(2011): AlexaCRM\CRMToolkit\Client->getSoapResponse('https://mycrm.u...', '<s:Envelope xml...') #1 C:\xampp\htdocs\uic\alexacrm\php-crm-toolkit\src\Client.php(1679): AlexaCRM\CRMToolkit\Client->attemptSoapResponse('organization', Object(Closure)) #2 C:\xampp\htdocs\uic\alexacrm\php-crm-toolkit\src\Entity.php(457): AlexaCRM\CRMToolkit\Client->create(Object(AlexaCRM\CRMToolkit\Entity)) #3 C:\xampp\htdocs\uic\test.php(67): AlexaCRM\CRMToolkit\Entity->create() #4 {main} thrown in C:\xampp\htdocs\uic\alexacrm\php-crm-toolkit\src\Client.php on line 1159

**Comment by georged** [comment]
The message is self-explanatory - the user is missing Append To privilege on`new_produituic` entity. 

Thanks

**Comment by Tidada** [comment]
$contact = $service->entity('contact');
$contact->firstname='testproduits';
$contact->new_produit_demande= new EntityReference('new_produituic', new guid('00f1b74b-645c-e911-80c1-005056aa3849'));
$contactId = $contact->create();

this one is correcT?(Fatal error: Class 'guid' not found in)
 because i m trying to translate c# code to php

**Comment by Tidada** [comment]
and about the first error i want to add a product id from entity 'new_produituic' to 'contact' entity 

Can you help ?
