### ISSUE TITLE
cli-contact example not working

### ISSUE THREAD

**Issue by opripentele** [AlexaCRM/php-crm-toolkit#9]
When running the cli-contact with email as an argument, I get the following error:

PHP Catchable fatal error:  Object of class AlexaCRM\CRMToolkit\KeyAttributes could not be converted to string in /php-crm-toolkit-master/src/Entity.php on line 1297

**Comment by wizardist** [comment]
@opripentele indeed. We started caching records in-memory, but fell short of generating correct cache keys for records with key attributes. Bare with us!
