### ISSUE TITLE
CRM connectivity issue

### ISSUE THREAD

**Issue by muralirly** [AlexaCRM/php-crm-toolkit#91]
I am not able to connect to CRM online instance. Tried all the possible combination of checkboxes and urls. Any help would be appreicated.
The url was from CRM-->Settings--Developer resources. I am able to connect to this URL from XrmToolbox.

Error: 

 {"credentials":["https://xxx.api.crm.dynamics.com","xxxx@xxxx.org"],"exception":"[object] (InvalidArgumentException(code: 0): Cannot resolve CRM region: check CRM server url at /home/treeho51/public_html/wp-content/plugins/integration-dynamics/vendor/alexacrm/php-crm-toolkit/src/Settings.php:327)"} []

**Comment by wizardist** [comment]
Hi @muralirly 

Try the organization URL first, e.g. `https://xxx.crm.dynamics.com`.

HTH

**Comment by muralirly** [comment]
Hi, Thanks for your reply.
I tried that first.
Same error.

**Comment by muralirly** [comment]
In xrmtool box I used https://xxx.api.crm.dynamics.com . and it worked.

**Comment by georged** [comment]
hi there

Is your region really crm.dynamics.com? I wonder itf it's the new crm12 region? What's your full org url?

Thanks
George

**Comment by georged** [comment]
@muralirly 

we need your org url to investigate. If you don't want to submit it here, you can email it to support@alexacrm.com

Thanks
George

**Comment by muralirly** [comment]
@georged 

Sent you org url to your support email.

Thanks,
Murali

**Comment by georged** [comment]
Hi Murali,

as per our email exchange, looks like your WordPress hosting server cannot resolve your authority server URL. This information is available when logging is set to Debug level.

Thanks

**Comment by muralirly** [comment]
Hi George,

Thanks! Let me check with them.

Regards,
Murali
