### ISSUE TITLE
URGENT: Update Notes Field on Dynamics

### ISSUE THREAD

**Issue by maulik-vinchhi** [AlexaCRM/php-crm-toolkit#92]
Hi Team,

I wanted to know if I can populate "Notes" field of Lead entity on Dynamics?

I tried to search online but not sure how I can do that.
Can you please let me know ASAP how I can add my data using this toolkit on Notes field.

Thanks

**Comment by maulik-vinchhi** [comment]
Hi Team,

Can I have your input on my above query?

**Comment by georged** [comment]
@maulik-vinchhi

Notes as in text? That'd be description field. 

Notes as in multiple attached notes and files? That'd be annotation entity. The only trick about annotation entity is that file content needs to be bas64 encoded. 

Hth
George
