### ISSUE TITLE
Metadata request returned a 403 code

### ISSUE THREAD

**Issue by bjohnson-healthinsight** [AlexaCRM/php-crm-toolkit#94]
Just trying to query accounts; this worked until we upgraded our 365 instance to a newer version recently. https://XYZ.api.crm.dynamics.com/api/data/v9.1/

"Metadata request returned a 403 code in AlexaCRM\WebAPI\Client->retrieveViaQueryByAttribute() (line 491 of .../dynamics-webapi-toolkit/src/WebAPI/Client.php)"

**Comment by bjohnson-healthinsight** [comment]
Closing; this is not a code issue. My apologies. This reflected the need to set up an application user in CRM, which I had forgotten about in the new system.

**Comment by georged** [comment]
No problem, @bjohnson-healthinsight, thanks for handling it :)
Didn't you mean to post under https://github.com/AlexaCRM/dynamics-webapi-toolkit/issues/, anyway?
