### ISSUE TITLE
Where to retrieve login credentials?

### ISSUE THREAD

**Issue by CaptainCannabis** [AlexaCRM/php-crm-toolkit#95]
Hi,

i am lost. I want to retrieve data like contacts and opportunities from MS Dynamics CRM. My first try used the dynamics-webapi-toolkit. No success. I get an error "undefined index 0" when i try to call the api with the credentials that are displayed in Azure.

confusion begins here. I don't know if they want me to use the App, Directory or Object-ID?

![Image 1](https://user-images.githubusercontent.com/5312061/62936542-63633400-bdca-11e9-9f8a-56d9eb7f3bf4.png)

So i switched to this repo.  But same problem here.

```
$contactId = '1d2fc62f-1c56-448b-b546-edfb6d6fec5c';
$options = [
    'serverUrl' => 'https://org.crmN.dynamics.com',
    'username' => 'portal@org.onmicrosoft.com',
    'password' => 'portalPassword',
    'authMode' => 'OnlineFederation',
];

```
Where to retrieve or configurate those values? Which Endpoint to use?

![Image 2](https://user-images.githubusercontent.com/5312061/62936789-fc924a80-bdca-11e9-816e-621790ce2f17.png)

Please enlighten me :)

**Comment by CaptainCannabis** [comment]
https://community.adxstudio.com/products/adxstudio-portals/installation-operations-guide/registering-license-keys/how-to-find-organization-service-url-in-dynamics-crm/

**Comment by georged** [comment]
Hey @CaptainCannabis 

that article is about org service URL. You'd still need username and password to connect using that toolkit. For https://github.com/alexacrm/dynamics-webapi-toolkit you can follow [the tutorial](https://github.com/AlexaCRM/dynamics-webapi-toolkit/wiki/Tutorial). The required steps outside of the toolkit are registering the app id and then creating app user for that app id. As per the documentation:

> The toolkit uses server-to-server authentication and application users supported by Dynamics 365. Read the walkthroughs how to [register your application on Azure AD](https://docs.microsoft.com/en-us/dynamics365/customer-engagement/developer/walkthrough-multi-tenant-server-server-authentication#register-your-application-on-azure-ad) and how to [create a Dynamics 365 application user](https://docs.microsoft.com/en-us/dynamics365/customer-engagement/developer/use-multi-tenant-server-server-authentication#manually-create-a-includepncrm2016shortestincludespn-crm-2016-shortestmd-application-user).
