### ISSUE TITLE
Uncaught Exception: Could not find definition of Service <OrganizationService> in provided WSDL in php-crm-toolkit/src/Client.php:664

### ISSUE THREAD

**Issue by basd82** [AlexaCRM/php-crm-toolkit#96]
Hi i am trying to connect to onpremis CRM server but i can't get it work, first issue as ignoressl setting but nu ig get this error:

root@my-server:/disk/site/ontwikkel/crm/vendor/alexacrm/php-crm-toolkit/examples# php cli-whoami.php
PHP Fatal error:  Uncaught Exception: Could not find definition of Service <OrganizationService> in provided WSDL in /disk/site/ontwikkel/crm/vendor/alexacrm/php-crm-toolkit/src/Client.php:664
Stack trace:
#0 /disk/site/ontwikkel/crm/vendor/alexacrm/php-crm-toolkit/src/Client.php(304): AlexaCRM\CRMToolkit\Client->findSecurityPolicy(Object(DOMDocument), 'OrganizationSer...')
#1 /disk/site/ontwikkel/crm/vendor/alexacrm/php-crm-toolkit/src/Client.php(623): AlexaCRM\CRMToolkit\Client->getOrganizationAuthenticationAddress()
#2 /disk/site/ontwikkel/crm/vendor/alexacrm/php-crm-toolkit/src/Client.php(159): AlexaCRM\CRMToolkit\Client->getFederationSecurityURI('organization')
#3 /disk/site/ontwikkel/crm/vendor/alexacrm/php-crm-toolkit/examples/cli-whoami.php(36): AlexaCRM\CRMToolkit\Client->__construct(Object(AlexaCRM\CRMToolkit\Settings))
#4 {main}
  thrown in /disk/site/ontwikkel/crm/vendor/alexacrm/php-crm-toolkit/src/Client.php on line 664

**Comment by basd82** [comment]
my config.php

<?php
/**
 * Copyright (c) 2016 AlexaCRM.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as
 * published by the Free Software Foundation, version 3.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Lesser Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

return [
    // Dynamics CRM URL
    'serverUrl' => 'https://domain.name.local:444',

    // System user name
    'username'  => 'secretdomain\secret_user',

    // System user password
    'password'  => 'top-secret',

    // CRM type (OnlineFederation for CRM Online, Federation for IFD)
    'authMode'  => 'Federation',

    'ignoreSslErrors' => true
];

**Comment by georged** [comment]
Hi @basd82 

what version of CRM are you running? 

Can you try accessing https://domain.name.local:444/XRMServices/2011/Organization.svc?wsdl and let us know what comes back?

If you cannot access that URL then open CRM, navigate to Settings > Customizations > Developer Resources and let us know what's the endpoint address for the organization service.

Thanks

**Comment by basd82** [comment]
We se crm 2011

 

<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsx="http://schemas.xmlsoap.org/ws/2004/09/mex" xmlns:i0="http://schemas.microsoft.com/xrm/2011/Contracts/Services" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:wsa10="http://www.w3.org/2005/08/addressing" xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:wsap="http://schemas.xmlsoap.org/ws/2004/08/addressing/policy" xmlns:msc="http://schemas.microsoft.com/ws/2005/12/wsdl/contract"xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:wsa="http://schemas.xmlsoap.org/ws/2004/08/addressing" xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata" xmlns:xsd="http://www.w3.org/2001/XMLSchema"xmlns:tns="http://schemas.microsoft.com/xrm/2011/Contracts" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsaw="http://www.w3.org/2006/05/addressing/wsdl" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" name="OrganizationService"targetNamespace="http://schemas.microsoft.com/xrm/2011/Contracts">

<wsdl:import namespace="http://schemas.microsoft.com/xrm/2011/Contracts/Services" location="https://domain.name.local:444/XRMServices/2011/Organization.svc?wsdl=wsdl0"/>

<wsdl:types/>

<wsdl:service name="OrganizationService">

<wsdl:port name="CustomBinding_IOrganizationService" binding="i0:CustomBinding_IOrganizationService">

<soap12:address location="https://domain.name.local:444/XRMServices/2011/Organization.svc"/>

<wsa10:EndpointReference>

<wsa10:Address>

https://domain.name.local:444/XRMServices/2011/Organization.svc

</wsa10:Address>

</wsa10:EndpointReference>

</wsdl:port>

</wsdl:service>

</wsdl:definitions>

 

Van: George Doubinski <notifications@github.com> 
Verzonden: woensdag 14 augustus 2019 01:36
Aan: AlexaCRM/php-crm-toolkit <php-crm-toolkit@noreply.github.com>
CC: Bas van den DIkkenberg <bas@dikkenberg.net>; Mention <mention@noreply.github.com>
Onderwerp: Re: [AlexaCRM/php-crm-toolkit] Uncaught Exception: Could not find definition of Service <OrganizationService> in provided WSDL in php-crm-toolkit/src/Client.php:664 (#96)

 

Hi @basd82 <https://github.com/basd82> 

what version of CRM are you running?

Can you try accessing https://domain.name.local:444/XRMServices/2011/Organization.svc?wsdl and let us know what comes back?

If you cannot access that URL then open CRM, navigate to Settings > Customizations > Developer Resources and let us know what's the endpoint address for the organization service.

Thanks

**Comment by basd82** [comment]
I resolved the iseu the package php-soap was missen 

 

Van: Bas van den Dikkenberg <bas@dikkenberg.net> 
Verzonden: donderdag 15 augustus 2019 15:44
Aan: 'AlexaCRM/php-crm-toolkit' <reply@reply.github.com>; 'AlexaCRM/php-crm-toolkit' <php-crm-toolkit@noreply.github.com>
CC: 'Mention' <mention@noreply.github.com>
Onderwerp: RE: [AlexaCRM/php-crm-toolkit] Uncaught Exception: Could not find definition of Service <OrganizationService> in provided WSDL in php-crm-toolkit/src/Client.php:664 (#96)

 

We se crm 2011

 

<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsx="http://schemas.xmlsoap.org/ws/2004/09/mex" xmlns:i0="http://schemas.microsoft.com/xrm/2011/Contracts/Services" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:wsa10="http://www.w3.org/2005/08/addressing" xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:wsap="http://schemas.xmlsoap.org/ws/2004/08/addressing/policy" xmlns:msc="http://schemas.microsoft.com/ws/2005/12/wsdl/contract"xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:wsa="http://schemas.xmlsoap.org/ws/2004/08/addressing" xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata" xmlns:xsd="http://www.w3.org/2001/XMLSchema"xmlns:tns="http://schemas.microsoft.com/xrm/2011/Contracts" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsaw="http://www.w3.org/2006/05/addressing/wsdl" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" name="OrganizationService"targetNamespace="http://schemas.microsoft.com/xrm/2011/Contracts">

<wsdl:import namespace="http://schemas.microsoft.com/xrm/2011/Contracts/Services" location="https://domain.name.local:444/XRMServices/2011/Organization.svc?wsdl=wsdl0"/>

<wsdl:types/>

<wsdl:service name="OrganizationService">

<wsdl:port name="CustomBinding_IOrganizationService" binding="i0:CustomBinding_IOrganizationService">

<soap12:address location="https://domain.name.local:444/XRMServices/2011/Organization.svc"/>

<wsa10:EndpointReference>

<wsa10:Address>

https://domain.name.local:444/XRMServices/2011/Organization.svc

</wsa10:Address>

</wsa10:EndpointReference>

</wsdl:port>

</wsdl:service>

</wsdl:definitions>

 

Van: George Doubinski <notifications@github.com <mailto:notifications@github.com> > 
Verzonden: woensdag 14 augustus 2019 01:36
Aan: AlexaCRM/php-crm-toolkit <php-crm-toolkit@noreply.github.com <mailto:php-crm-toolkit@noreply.github.com> >
CC: Bas van den DIkkenberg <bas@dikkenberg.net <mailto:bas@dikkenberg.net> >; Mention <mention@noreply.github.com <mailto:mention@noreply.github.com> >
Onderwerp: Re: [AlexaCRM/php-crm-toolkit] Uncaught Exception: Could not find definition of Service <OrganizationService> in provided WSDL in php-crm-toolkit/src/Client.php:664 (#96)

 

Hi @basd82 <https://github.com/basd82> 

what version of CRM are you running?

Can you try accessing https://domain.name.local:444/XRMServices/2011/Organization.svc?wsdl and let us know what comes back?

If you cannot access that URL then open CRM, navigate to Settings > Customizations > Developer Resources and let us know what's the endpoint address for the organization service.

Thanks

**Comment by georged** [comment]
@basd82 great to see it resolved!
