### ISSUE TITLE
Hiding message error

### ISSUE THREAD

**Issue by dantedantas** [AlexaCRM/php-crm-toolkit#97]
Dear All, 

Please, could someone explain to me how and where could I hide an error message? E.g.: I would like to send me an email when an error happened, but I would like to show a "friendly" message to the final user.

**Another important point** is that if you scroll the message error, you could find the user and the related password that I am using.

![image](https://user-images.githubusercontent.com/10854571/65147666-e5c0c280-da1e-11e9-9ae5-27f8eefc75c1.png)

Thank you in advance.

**Comment by dantedantas** [comment]
Hello,

I "solved" with a try-catch.

```
try
{
    $incidents = $client->retrieveMultiple($fetchxmlinc, xxxxxxxxxxx);
}
catch (Exception $e) {
    echo 'ATTENTION!<br><br>'.$e->getMessage().'<br><br>';
    exit;
}
```
Has another "elegant" way to solve this issue?

Thank you.

**Comment by georged** [comment]
@dantedantas 

glad you have it resolved. That looks like a `var_dump` result (which we don't have anywhere), I'd recommend checking your code and settings that you're not using it for uncaught errors. 

Yes, credentials would be in a dump, however, when logging, all sensitive information is stripped out.

HTH
George
