### ISSUE TITLE
Cannot resolve CRM region: check CRM server url

### ISSUE THREAD

**Issue by sas-adilis** [AlexaCRM/php-crm-toolkit#99]
Hi,
Using your librairie i have an error using default example. My instance URL is on CRM12 and i saw in alexacrm/php-crm-toolkit/src/Settings.php there is no entry for crm12 in private static $crmRegionMapping

Could you help me ?

**Comment by sas-adilis** [comment]
urn:crmfra:dynamics.com

**Comment by wizardist** [comment]
3b17c3e should allow connecting to Dynamics organizations deployed in France.

**Comment by sas-adilis** [comment]
It works
Thank you
